'use client';

import Link from 'next/link';
import { ChangeEvent, useEffect, useState } from 'react';

type DocumentReference = { name?: string; document_type?: string };
type Verification = { status: string; legal_name: string | null; business_name: string | null; registration_number: string | null; reviewer_notes: string | null; submitted_at: string | null; document_storage_references: DocumentReference[] };
type Form = { name: string; logo_url: string | null; description: string; contact_person: string; contact_email: string; contact_phone: string; address: string; website: string; legal_name: string; business_name: string; registration_number: string; facebook: string; instagram: string; other: string };
const empty: Form = { name: '', logo_url: null, description: '', contact_person: '', contact_email: '', contact_phone: '', address: '', website: '', legal_name: '', business_name: '', registration_number: '', facebook: '', instagram: '', other: '' };

export default function VerificationPage() {
  const [form, setForm] = useState<Form>(empty);
  const [verification, setVerification] = useState<Verification | null>(null);
  const [governmentId, setGovernmentId] = useState<File | null>(null);
  const [supportingDocuments, setSupportingDocuments] = useState<File[]>([]);
  const [message, setMessage] = useState('Loading onboarding…');
  const [busy, setBusy] = useState(false);

  async function load() {
    const [orgResponse, verificationResponse] = await Promise.all([fetch('/api/organizer/organization'), fetch('/api/organizer/verification')]);
    const organization = await orgResponse.json().catch(() => ({})); const verificationBody = await verificationResponse.json().catch(() => ({}));
    if (!orgResponse.ok || !verificationResponse.ok) { setMessage(organization.error ?? verificationBody.error ?? 'Onboarding could not be loaded.'); return; }
    const links = organization.social_links ?? {};
    setForm({ name: organization.name ?? '', logo_url: organization.logo_url ?? null, description: organization.description ?? '', contact_person: organization.contact_person ?? '', contact_email: organization.contact_email ?? '', contact_phone: organization.contact_phone ?? '', address: organization.address ?? '', website: organization.website ?? '', legal_name: verificationBody?.legal_name ?? '', business_name: verificationBody?.business_name ?? '', registration_number: verificationBody?.registration_number ?? '', facebook: links.facebook ?? '', instagram: links.instagram ?? '', other: links.other ?? '' });
    setVerification(verificationBody); setMessage('');
  }
  useEffect(() => { void load(); }, []);
  function update(key: keyof Form, value: string) { setForm((current) => ({ ...current, [key]: value })); }
  async function uploadLogo(event: ChangeEvent<HTMLInputElement>) { const input = event.currentTarget; const file = input.files?.[0]; if (!file) return; setBusy(true); const data = new FormData(); data.append('file', file); const response = await fetch('/api/organizer/organization/logo', { method: 'POST', body: data }); const body = await response.json().catch(() => ({})); input.value = ''; setBusy(false); if (response.ok) { setForm((current) => ({ ...current, logo_url: body.logo_url })); setMessage('Logo uploaded and saved.'); } else setMessage(body.error ?? 'Logo upload failed.'); }
  async function submit() { setBusy(true); setMessage('Saving profile and preparing documents…'); const draft = await fetch('/api/organizer/verification', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ legal_name: form.legal_name || null, business_name: form.business_name || null, registration_number: form.registration_number || null }) }); if (!draft.ok) { const body = await draft.json().catch(() => ({})); setBusy(false); setMessage(body.error ?? 'Verification draft could not be saved.'); return; } const files = governmentId ? [{ file: governmentId, type: 'government_id' }] : []; files.push(...supportingDocuments.map((file) => ({ file, type: 'supporting_document' }))); for (const item of files) { const data = new FormData(); data.append('file', item.file); data.append('document_type', item.type); const response = await fetch('/api/organizer/verification/documents', { method: 'POST', body: data }); if (!response.ok) { const body = await response.json().catch(() => ({})); setBusy(false); setMessage(body.error ?? 'Document upload failed.'); return; } } const response = await fetch('/api/organizer/onboarding/submit', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ organization: { name: form.name, logo_url: form.logo_url, description: form.description, contact_person: form.contact_person, contact_email: form.contact_email, contact_phone: form.contact_phone, address: form.address || null, website: form.website || null, social_links: { facebook: form.facebook, instagram: form.instagram, other: form.other } }, verification: { legal_name: form.legal_name, business_name: form.business_name || null, registration_number: form.registration_number || null } }) }); const body = await response.json().catch(() => ({})); await load(); setBusy(false); setMessage(response.ok ? 'Submitted for review.' : body.error ?? 'Submission failed.'); }
  const status = verification?.status ?? 'draft'; const locked = status === 'pending_review' || status === 'approved' || status === 'rejected'; const documents = verification?.document_storage_references ?? []; const hasGovernmentId = documents.some((document) => document.document_type === 'government_id'); const ready = Boolean(form.name.trim() && form.logo_url && form.description.trim() && form.contact_person.trim() && form.contact_email.trim() && form.contact_phone.trim() && form.legal_name.trim() && (hasGovernmentId || governmentId));
  const profileFields = [['name', 'Organization Name'], ['contact_person', 'Contact Person'], ['contact_email', 'Contact Email'], ['contact_phone', 'Contact Phone']] as const;
  if (status === 'pending_review') return <main className="flex min-h-[70vh] items-start justify-center p-6 sm:items-center"><section className="w-full max-w-xl rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex items-start justify-between gap-4"><div><h1 className="text-xl font-bold text-slate-950">Organizer verification</h1><p className="mt-2 text-sm text-slate-500">Submitted {verification?.submitted_at ? new Date(verification.submitted_at).toLocaleDateString() : 'date unavailable'}. We&apos;ll notify you by email once a decision is made.</p></div><div className="flex shrink-0 items-center gap-3"><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-800">Pending review</span><button type="button" aria-label="More options" className="text-lg font-bold tracking-widest text-slate-400">···</button></div></div><div className="mt-6 rounded-xl bg-slate-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Organization</p><p className="mt-1 text-lg font-bold text-slate-950">{form.name || 'Organization'}</p><p className="mt-1 text-sm text-slate-500">{[form.contact_person, form.contact_email, form.contact_phone].filter(Boolean).join(' · ')}</p></div><div className="my-6 border-t border-slate-200" /><section><h2 className="text-sm font-bold text-slate-950">Verification details</h2><dl className="mt-3 divide-y divide-slate-100 text-sm"><div className="flex justify-between gap-6 py-2"><dt className="text-slate-500">Legal name</dt><dd className="text-right font-medium text-slate-900">{form.legal_name || 'Not provided'}</dd></div><div className="flex justify-between gap-6 py-2"><dt className="text-slate-500">Business name</dt><dd className={form.business_name ? 'text-right font-medium text-slate-900' : 'text-right text-slate-400'}>{form.business_name || 'Not provided'}</dd></div><div className="flex justify-between gap-6 py-2"><dt className="text-slate-500">Registration number</dt><dd className={form.registration_number ? 'text-right font-medium text-slate-900' : 'text-right text-slate-400'}>{form.registration_number || 'Not provided'}</dd></div></dl></section><div className="my-6 border-t border-slate-200" /><section><h2 className="text-sm font-bold text-slate-950">Documents</h2><ul className="mt-3 space-y-2">{documents.length ? documents.map((document, index) => <li key={`${document.name}-${index}`} className="flex items-center gap-2 text-sm text-slate-700"><span aria-hidden="true" className="text-slate-400">▧</span><span>{document.name || 'Uploaded document'}</span></li>) : <li className="text-sm text-slate-400">No documents listed.</li>}</ul></section></section></main>;
  if (status === 'approved') return <main className="mx-auto max-w-3xl space-y-6 p-6"><h1 className="text-3xl font-semibold">Organizer onboarding approved</h1><p className="rounded border border-emerald-200 bg-emerald-50 p-4">Your organization is approved. You can now create your first event.</p><Link href="/organizer/events" className="inline-block rounded bg-black px-4 py-2 text-white">Create Your First Event</Link><p className="text-sm text-gray-600">Edit public information at <Link className="underline" href="/organizer/organization">Organization Profile</Link>.</p></main>;
  return <main className="mx-auto max-w-4xl space-y-6 p-6"><header><p className="text-sm font-semibold uppercase tracking-[0.18em] text-orange-600">Organizer onboarding</p><h1 className="text-3xl font-semibold">Organization setup &amp; verification</h1><p className="mt-1 text-sm text-gray-600">Complete both sections before submitting your organizer account for review.</p></header><p className="rounded border p-3 text-sm">Status: <strong>{status === 'needs_changes' ? 'Needs changes' : status === 'pending_review' ? 'Pending Review' : status}</strong>{verification?.submitted_at && ` · Submitted ${new Date(verification.submitted_at).toLocaleDateString()}`}</p>{message && <p role="status" className="text-sm">{message}</p>}{verification?.reviewer_notes && <p className="rounded border border-amber-300 bg-amber-50 p-3 text-sm">Admin feedback: {verification.reviewer_notes}</p>}
    <section className="grid gap-4 rounded border bg-white p-6 sm:grid-cols-2"><h2 className="text-xl font-semibold sm:col-span-2">Public information</h2>{profileFields.map(([key, label]) => <label key={key} className="block text-sm">{label}<input disabled={locked || busy} required value={form[key]} onChange={(event) => update(key, event.target.value)} className="mt-1 w-full rounded border p-2" /></label>)}<label className="block text-sm sm:col-span-2">Description<textarea disabled={locked || busy} required value={form.description} onChange={(event) => update('description', event.target.value)} className="mt-1 min-h-28 w-full rounded border p-2" /></label><label className="block text-sm">Address (optional)<input disabled={locked || busy} value={form.address} onChange={(event) => update('address', event.target.value)} className="mt-1 w-full rounded border p-2" /></label><label className="block text-sm">Website (optional)<input disabled={locked || busy} type="url" value={form.website} onChange={(event) => update('website', event.target.value)} className="mt-1 w-full rounded border p-2" /></label><label className="block text-sm sm:col-span-2">Organization Logo<input disabled={locked || busy} required={!form.logo_url} type="file" accept="image/jpeg,image/png,image/webp" onChange={uploadLogo} className="mt-1 block w-full rounded border p-2" />{form.logo_url && <img src={form.logo_url} alt="Organization logo" className="mt-2 h-20 w-20 rounded object-cover" />}</label><label className="block text-sm">Facebook URL<input disabled={locked || busy} type="url" value={form.facebook} onChange={(event) => update('facebook', event.target.value)} className="mt-1 w-full rounded border p-2" /></label><label className="block text-sm">Instagram URL<input disabled={locked || busy} type="url" value={form.instagram} onChange={(event) => update('instagram', event.target.value)} className="mt-1 w-full rounded border p-2" /></label><label className="block text-sm sm:col-span-2">Other Social URL<input disabled={locked || busy} type="url" value={form.other} onChange={(event) => update('other', event.target.value)} className="mt-1 w-full rounded border p-2" /></label></section>
    <section className="grid gap-4 rounded border bg-white p-6 sm:grid-cols-2"><h2 className="text-xl font-semibold sm:col-span-2">For RaceDeck verification</h2><label className="block text-sm sm:col-span-2">Legal Name<input disabled={locked || busy} required value={form.legal_name} onChange={(event) => update('legal_name', event.target.value)} className="mt-1 w-full rounded border p-2" /></label><label className="block text-sm">Business Name (optional)<input disabled={locked || busy} value={form.business_name} onChange={(event) => update('business_name', event.target.value)} className="mt-1 w-full rounded border p-2" /></label><label className="block text-sm">Registration Number (optional)<input disabled={locked || busy} value={form.registration_number} onChange={(event) => update('registration_number', event.target.value)} className="mt-1 w-full rounded border p-2" /></label><label className="block text-sm sm:col-span-2">Valid Government ID (required)<input disabled={locked || busy || hasGovernmentId} required={!hasGovernmentId} type="file" accept="application/pdf,image/jpeg,image/png" onChange={(event) => setGovernmentId(event.target.files?.[0] ?? null)} className="mt-1 block w-full rounded border p-2" />{hasGovernmentId && <span className="mt-1 block text-xs text-emerald-700">Government ID uploaded.</span>}</label><label className="block text-sm sm:col-span-2">Additional supporting documents (optional)<input disabled={locked || busy} multiple type="file" accept="application/pdf,image/jpeg,image/png" onChange={(event) => setSupportingDocuments(Array.from(event.target.files ?? []))} className="mt-1 block w-full rounded border p-2" /></label>{documents.length > 0 && <p className="text-sm text-gray-600 sm:col-span-2">Saved documents: {documents.map((document) => document.name ?? 'Document').join(', ')}</p>}</section>
    <button disabled={busy || locked || !ready} onClick={() => void submit()} className="rounded bg-black px-4 py-2 text-white disabled:opacity-50">{busy ? 'Submitting…' : status === 'needs_changes' ? 'Resubmit for Review' : 'Submit for Review'}</button>{!ready && !locked && <p className="text-xs text-gray-600">Complete the required fields, upload a logo, legal name, and government ID.</p>}</main>;
}
