/* eslint-disable @next/next/no-img-element */
'use client';
import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';

type DocumentReference = { path: string; name?: string; signed_url?: string | null };
type Application = { status: string; reviewer_notes: string | null; legal_name: string | null; business_name: string | null; registration_number: string | null; submitted_at: string | null; document_storage_references: DocumentReference[]; organizations: { name: string; logo_url: string | null; description: string | null; contact_person: string | null; contact_email: string | null; contact_phone: string | null; address: string | null; website: string | null; account_status: string; verification_status: string } };

export default function OrganizerReviewClient({ organizerId }: { organizerId: string }) {
  const [item, setItem] = useState<Application | null>(null); const [notes, setNotes] = useState(''); const [message, setMessage] = useState('Loading application…'); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const response = await fetch(`/api/admin/organizers/${organizerId}`); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error ?? 'Application could not be loaded'); setItem(data); setNotes(data.reviewer_notes ?? ''); setMessage(''); } catch (error) { setMessage(error instanceof Error ? error.message : 'Application could not be loaded'); } }, [organizerId]);
  useEffect(() => { void load(); }, [load]);
  async function review(status: 'approved' | 'needs_changes' | 'rejected') { if (status !== 'approved' && !notes.trim()) { setMessage(status === 'rejected' ? 'A rejection reason is required.' : 'Feedback is required when requesting changes.'); return; } setBusy(true); const response = await fetch(`/api/admin/organizers/${organizerId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status, reviewer_notes: notes.trim() || null }) }); const data = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) { setMessage(data.error ?? 'Review failed.'); return; } setMessage('Review decision saved and organizer notification queued.'); await load(); }
  if (!item) return <main className="mx-auto max-w-4xl p-6"><Link href="/admin/organizers" className="text-sm underline">Back to applications</Link><p role="status" className="mt-6">{message}</p></main>;
  const organization = item.organizations;
  return <main className="mx-auto max-w-4xl space-y-6 p-6"><Link href="/admin/organizers" className="text-sm underline">Back to applications</Link><header><h1 className="text-2xl font-semibold">Organizer Verification Review</h1><p className="text-sm text-gray-600">Submitted {item.submitted_at ? new Date(item.submitted_at).toLocaleString() : 'date unavailable'}</p></header>{message && <p role="status" className="text-sm">{message}</p>}<section className="space-y-2 rounded border p-4"><div className="flex items-center gap-3">{organization.logo_url && <img src={organization.logo_url} alt="" className="h-12 w-12 rounded object-cover"/>}<h2 className="font-semibold">{organization.name}</h2></div><p>{organization.description ?? 'No description provided.'}</p><p className="text-sm">Contact: {organization.contact_person ?? 'Not provided'} · {organization.contact_email ?? 'No email'} · {organization.contact_phone ?? 'No phone'}</p><p className="text-sm">Address: {organization.address ?? 'Not provided'}</p>{organization.website && <a href={organization.website} target="_blank" rel="noreferrer" className="text-sm underline">{organization.website}</a>}<p className="text-sm">Verification status: <strong>{item.status}</strong></p><p className="text-sm">Account status: <strong>{organization.account_status}</strong></p><p className="text-sm">Legal details: {item.legal_name ?? 'Not provided'} · {item.business_name ?? 'Not provided'} · {item.registration_number ?? 'No registration number'}</p></section><section className="rounded border p-4"><h2 className="font-semibold">Verification documents</h2><div className="mt-3 space-y-2">{item.document_storage_references.length ? item.document_storage_references.map(document => document.signed_url ? <a key={document.path} href={document.signed_url} target="_blank" rel="noreferrer" className="block text-sm underline">{document.name ?? document.path}</a> : <p key={document.path} className="text-sm text-red-600">Signed URL unavailable for {document.name ?? document.path}</p>) : <p className="text-sm text-gray-600">No documents submitted.</p>}</div></section><section className="space-y-3 rounded border p-4"><h2 className="font-semibold">Review decision</h2><label className="block text-sm">Feedback or rejection reason<textarea value={notes} onChange={event => setNotes(event.target.value)} maxLength={5000} className="mt-1 min-h-28 w-full rounded border p-2" placeholder="Required for Request Changes and Reject"/></label><div className="flex flex-wrap gap-2"><button disabled={busy} onClick={() => review('approved')} className="rounded bg-black px-4 py-2 text-sm text-white">Approve</button><button disabled={busy} onClick={() => review('needs_changes')} className="rounded border px-4 py-2 text-sm">Request Changes</button><button disabled={busy} onClick={() => review('rejected')} className="rounded border px-4 py-2 text-sm">Reject</button></div></section></main>;
}
