import { NextResponse } from 'next/server';
import { z } from 'zod';
import { hasPermission, loadAuthContext } from '@/lib/auth/permissions';
import { createAdminClient } from '@/lib/supabase/admin';
import { createClient } from '@/lib/supabase/server';

const settingSchema = z.object({ reminder_key: z.string().trim().min(1).max(80), reminder_type: z.enum(['race_reminder', 'race_tomorrow', 'race_kit_claiming_deadline', 'custom']), lead_time_minutes: z.number().int().positive(), enabled: z.boolean(), instructions: z.string().trim().max(4000).nullable(), custom_schedule_at: z.string().datetime().nullable() });
const bodySchema = z.object({ settings: z.array(settingSchema).min(1).max(20) });

async function authorize(eventId: string) { const context = await loadAuthContext(); if (!context) return { response: NextResponse.json({ error: 'Authentication required' }, { status: 401 }) } as const; const membership = context.memberships[0]; if (!membership || !(await hasPermission(membership.organization_id, 'manage_email_reminders', eventId))) return { response: NextResponse.json({ error: 'Email reminder permission required' }, { status: 403 }) } as const; const supabase = await createClient(); const { data: event } = await supabase.from('events').select('id,organization_id,event_date').eq('id', eventId).eq('organization_id', membership.organization_id).maybeSingle(); if (!event) return { response: NextResponse.json({ error: 'Event not found' }, { status: 404 }) } as const; return { context, event } as const; }

export async function GET(_request: Request, { params }: { params: { eventId: string } }) { const result = await authorize(params.eventId); if ('response' in result) return result.response; const admin = createAdminClient(); const { data, error } = await admin.from('event_reminder_settings').select('id,event_id,reminder_key,reminder_type,lead_time_minutes,enabled,instructions,custom_schedule_at,created_at,updated_at').eq('event_id', params.eventId).eq('organization_id', result.event.organization_id).order('lead_time_minutes', { ascending: false }); if (error) { console.error('Unable to load reminder settings', error); return NextResponse.json({ error: 'Reminder settings could not be loaded' }, { status: 500 }); } return NextResponse.json({ event_date: result.event.event_date, settings: data ?? [] }); }

export async function POST(request: Request, { params }: { params: { eventId: string } }) { const result = await authorize(params.eventId); if ('response' in result) return result.response; const parsed = bodySchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: 'Invalid reminder settings' }, { status: 400 }); const keys = new Set<string>(); const eventStart = new Date(`${result.event.event_date}T00:00:00.000Z`); for (const setting of parsed.data.settings) { if (keys.has(setting.reminder_key)) return NextResponse.json({ error: 'Reminder keys must be unique' }, { status: 400 }); keys.add(setting.reminder_key); if ((setting.reminder_type === 'custom') !== (setting.custom_schedule_at !== null)) return NextResponse.json({ error: 'Custom reminders require a schedule date' }, { status: 400 }); if (setting.custom_schedule_at) { const scheduled = new Date(setting.custom_schedule_at); if (scheduled <= new Date() || scheduled >= eventStart) return NextResponse.json({ error: 'Custom reminder dates must be in the future and before the event' }, { status: 400 }); } }
  const admin = createAdminClient(); const rows = parsed.data.settings.map(setting => ({ ...setting, organization_id: result.event.organization_id, event_id: params.eventId })); const { data, error } = await admin.from('event_reminder_settings').upsert(rows, { onConflict: 'event_id,reminder_key' }).select('*'); if (error) { console.error('Unable to save reminder settings', error); return NextResponse.json({ error: 'Reminder settings could not be saved' }, { status: 500 }); } return NextResponse.json({ settings: data ?? [] }); }
