import { NextResponse } from 'next/server';
import { z } from 'zod';
import { hasPermission, loadAuthContext } from '@/lib/auth/permissions';
import { createAdminClient } from '@/lib/supabase/admin';
import { createClient } from '@/lib/supabase/server';

const input = z.object({ title: z.string().trim().min(1).max(200), message: z.string().trim().min(1).max(10000), audience: z.enum(['all_confirmed', 'category_confirmed']), race_category_id: z.string().uuid().nullable().optional(), delivery_channels: z.array(z.enum(['in_app', 'email'])).min(1), idempotency_key: z.string().trim().min(16).max(120) }).superRefine((value, context) => { if (value.audience === 'category_confirmed' && !value.race_category_id) context.addIssue({ code: 'custom', path: ['race_category_id'], message: 'Select a race category.' }); if (value.audience === 'all_confirmed' && value.race_category_id) context.addIssue({ code: 'custom', path: ['race_category_id'], message: 'Category is only valid for category announcements.' }); });

async function authorize(eventId: string) {
  const context = await loadAuthContext(); if (!context) return { response: NextResponse.json({ error: 'Authentication required' }, { status: 401 }) } as const;
  const internalAdmin = context.internalRoles.includes('admin') || context.internalRoles.includes('super_admin'); let membership = context.memberships[0]; for (const item of context.memberships) { if (await hasPermission(item.organization_id, 'manage_announcements', eventId)) { membership = item; break; } }
  if (!internalAdmin && (!membership || !(await hasPermission(membership.organization_id, 'manage_announcements', eventId)))) return { response: NextResponse.json({ error: 'Announcement management permission required' }, { status: 403 }) } as const;
  const supabase = await createClient(); let eventQuery = supabase.from('events').select('id,organization_id,name').eq('id', eventId); if (membership && !internalAdmin) eventQuery = eventQuery.eq('organization_id', membership.organization_id); const { data: event } = await eventQuery.maybeSingle(); if (!event) return { response: NextResponse.json({ error: 'Event not found' }, { status: 404 }) } as const;
  return { context, event, admin: createAdminClient() } as const;
}

export async function GET(_request: Request, { params }: { params: { eventId: string } }) {
  const auth = await authorize(params.eventId); if ('response' in auth) return auth.response; const { data, error } = await auth.admin.from('announcements').select('id,title,message,audience,race_category_id,delivery_channels,status,published_at,sent_at,created_at,updated_at,race_categories(id,name)').eq('event_id', params.eventId).eq('organization_id', auth.event.organization_id).order('created_at', { ascending: false }); if (error) return NextResponse.json({ error: 'Announcements could not be loaded' }, { status: 500 }); return NextResponse.json({ announcements: data ?? [] });
}

export async function POST(request: Request, { params }: { params: { eventId: string } }) {
  const auth = await authorize(params.eventId); if ('response' in auth) return auth.response; const parsed = input.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message ?? 'Invalid announcement' }, { status: 400 });
  const existing = await auth.admin.from('announcements').select('id,status,title,sent_at').eq('event_id', params.eventId).eq('organization_id', auth.event.organization_id).filter('metadata->>idempotency_key', 'eq', parsed.data.idempotency_key).maybeSingle(); if (existing.data) return NextResponse.json({ announcement: existing.data, duplicate: true });
  if (parsed.data.race_category_id) { const { data: category } = await auth.admin.from('race_categories').select('id').eq('id', parsed.data.race_category_id).eq('event_id', params.eventId).maybeSingle(); if (!category) return NextResponse.json({ error: 'Category does not belong to this event' }, { status: 400 }); }
  const { data: announcement, error: announcementError } = await auth.admin.from('announcements').insert({ organization_id: auth.event.organization_id, event_id: params.eventId, created_by: auth.context.user.id, title: parsed.data.title, message: parsed.data.message, audience: parsed.data.audience, race_category_id: parsed.data.race_category_id ?? null, delivery_channels: parsed.data.delivery_channels, status: 'draft', metadata: { idempotency_key: parsed.data.idempotency_key } }).select('id,title,status').single(); if (announcementError || !announcement) return NextResponse.json({ error: 'Announcement could not be created' }, { status: 500 });
  const recipientQuery = auth.admin.from('registrations').select('id,user_id,email,category_id').eq('event_id', params.eventId).eq('status', 'confirmed').not('user_id', 'is', null); const { data: recipients, error: recipientError } = parsed.data.audience === 'category_confirmed' ? await recipientQuery.eq('category_id', parsed.data.race_category_id as string) : await recipientQuery;
  if (recipientError) { await auth.admin.from('announcements').update({ status: 'failed', published_at: new Date().toISOString() }).eq('id', announcement.id); return NextResponse.json({ error: 'Announcement recipients could not be loaded' }, { status: 500 }); }
  try {
    const rows = recipients ?? []; if (parsed.data.delivery_channels.includes('in_app') && rows.length) { const { error } = await auth.admin.from('notifications').insert(rows.map((recipient) => ({ recipient_user_id: recipient.user_id as string, organization_id: auth.event.organization_id, event_id: params.eventId, registration_id: recipient.id, source_announcement_id: announcement.id, notification_type: 'organizer_announcement', title: parsed.data.title, body: parsed.data.message, idempotency_key: `announcement:${announcement.id}:${recipient.user_id}:in_app` }))); if (error) throw error; }
    if (parsed.data.delivery_channels.includes('email') && rows.length) { const { error } = await auth.admin.from('email_messages').upsert(rows.map((recipient) => ({ recipient_email: recipient.email, recipient_user_id: recipient.user_id, organization_id: auth.event.organization_id, event_id: params.eventId, registration_id: recipient.id, announcement_id: announcement.id, email_type: 'organizer_announcement', template_version: 1, template_snapshot: { type: 'organizer_announcement', announcement_id: announcement.id }, subject: parsed.data.title, status: 'queued', idempotency_key: `announcement:${announcement.id}:${recipient.user_id}:email` })), { onConflict: 'idempotency_key' }); if (error) throw error; }
    const { data: notifications } = parsed.data.delivery_channels.includes('in_app') && rows.length ? await auth.admin.from('notifications').select('id,recipient_user_id').eq('source_announcement_id', announcement.id) : { data: [] as Array<{ id: string; recipient_user_id: string }> }; if (notifications?.length) { const { error } = await auth.admin.from('notification_deliveries').insert(notifications.map((notification) => ({ notification_id: notification.id, recipient_user_id: notification.recipient_user_id, channel: 'in_app', status: 'queued', idempotency_key: `announcement:${announcement.id}:${notification.recipient_user_id}:in_app_delivery` }))); if (error && error.code !== '23505') throw error; }
    const now = new Date().toISOString(); await auth.admin.from('announcements').update({ status: 'sent', published_at: now, sent_at: now }).eq('id', announcement.id); await auth.admin.from('audit_logs').insert({ actor_user_id: auth.context.user.id, organization_id: auth.event.organization_id, event_id: params.eventId, action: 'announcement_created_and_sent', resource_type: 'communication', resource_id: announcement.id, new_values: { audience: parsed.data.audience, delivery_channels: parsed.data.delivery_channels, recipient_count: rows.length } }); return NextResponse.json({ announcement: { ...announcement, status: 'sent', sent_at: now }, recipient_count: rows.length }, { status: 201 });
  } catch (error) { console.error('Announcement delivery queue failed', error); await auth.admin.from('announcements').update({ status: 'failed', published_at: new Date().toISOString() }).eq('id', announcement.id); return NextResponse.json({ error: 'Announcement could not be queued for delivery' }, { status: 500 }); }
}
