'use client';

import { useEffect, useMemo, useState } from 'react';
import type { PublicEventDetails } from '@/lib/public/events';
import Link from 'next/link';

type Tab = 'details' | 'mechanics' | 'announcements' | 'faqs';
const unavailable = new Set(['closed', 'sold_out', 'not_yet_open']);
const label = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
const dateFormat = (value: string) => { const date = new Date(value.includes('T') ? value : `${value}T00:00:00`); return Number.isNaN(date.getTime()) ? 'Date to be announced' : new Intl.DateTimeFormat('en-PH', { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' }).format(date); };
const dateTimeFormat = (value: string) => { const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Date to be announced' : new Intl.DateTimeFormat('en-PH', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' }).format(date); };
const peso = (value: number) => `PHP ${value.toLocaleString('en-PH', { minimumFractionDigits: 2 })}`;

function Countdown({ eventDate, startTime }: { eventDate: string; startTime?: string | null }) {
  const [now, setNow] = useState(() => Date.now());
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, []);
  const targetDate = new Date(`${eventDate}T${startTime?.slice(0, 8) || '00:00:00'}`); const target = targetDate.getTime(); const remaining = Number.isNaN(target) ? 0 : Math.max(0, target - now); const totalSeconds = Math.floor(remaining / 1000); const currentDate = new Date(now); let months = Math.max(0, (targetDate.getFullYear() - currentDate.getFullYear()) * 12 + targetDate.getMonth() - currentDate.getMonth()); const monthStart = new Date(currentDate); monthStart.setMonth(monthStart.getMonth() + months); if (monthStart.getTime() > target) { months = Math.max(0, months - 1); monthStart.setTime(currentDate.getTime()); monthStart.setMonth(monthStart.getMonth() + months); } const remainder = Math.max(0, target - monthStart.getTime()); const values = [months, Math.floor(remainder / 86_400_000), Math.floor((totalSeconds / 3_600) % 24), Math.floor((totalSeconds / 60) % 60), totalSeconds % 60]; const labels = ['Months', 'Days', 'Hours', 'Mins.', 'Secs.'];
  return <div className="relative overflow-hidden rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><p className="relative text-center text-[10px] font-bold uppercase tracking-[0.16em] text-[#071b41]">Countdown until event starts</p><div className="relative mt-3 grid grid-cols-5 gap-1.5">{values.map((value, index) => <div key={labels[index]} className="text-center"><div className="grid h-10 place-items-center rounded-md bg-orange-600 text-lg font-black tabular-nums text-white shadow-sm">{String(value).padStart(2, '0')}</div><p className="mt-1 text-[9px] font-medium text-slate-600">{labels[index]}</p></div>)}</div></div>;
}

function splitContent(description: string | null) { const marker = /\nRace Mechanics\n/i; const parts = (description ?? '').split(marker); return { description: parts[0]?.trim() ?? '', mechanics: parts.slice(1).join('\nRace Mechanics\n').trim() }; }

function EventLogo({ event }: { event: PublicEventDetails }) { return event.logo_url ? <img src={event.logo_url} alt={`${event.name} logo`} className="h-full w-full object-contain" /> : event.banner_url ? <img src={event.banner_url} alt={`${event.name} thumbnail`} className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center bg-orange-50 text-4xl text-orange-500">Race</div>; }
function Status({ value }: { value: string }) { const styles = value === 'open' ? 'bg-emerald-50 text-emerald-700' : value === 'closed' || value === 'sold_out' ? 'bg-red-50 text-red-700' : 'bg-slate-100 text-slate-700'; return <span className={`inline-flex items-center gap-2 rounded-full px-3 py-1 text-xs font-bold ${styles}`}><span className="h-2 w-2 rounded-full bg-current" />{label(value)}</span>; }
function SocialIcon({ kind }: { kind: 'facebook' | 'instagram' }) { return kind === 'facebook' ? <svg viewBox="0 0 24 24" aria-hidden="true" className="h-5 w-5 fill-current"><path d="M14 8h3V4h-3c-3.31 0-5 1.98-5 5v3H6v4h3v8h4v-8h3.5l.5-4H13V9c0-.67.33-1 1-1Z" /></svg> : <svg viewBox="0 0 24 24" aria-hidden="true" className="h-5 w-5 fill-none stroke-current" strokeWidth="2"><rect x="3" y="3" width="18" height="18" rx="5" /><circle cx="12" cy="12" r="4" /><circle cx="17.5" cy="6.5" r="1" className="fill-current stroke-none" /></svg>; }
function safeSocialUrl(value: string | undefined) { if (!value) return null; try { const url = new URL(value); return url.protocol === 'http:' || url.protocol === 'https:' ? url.toString() : null; } catch { return null; } }

export function EventDetailsClient({ event }: { event: PublicEventDetails }) {
  const [tab, setTab] = useState<Tab>('details'); const [copied, setCopied] = useState(false);
  const tabs = useMemo(() => ([{ id: 'details' as const, name: 'Event Details' }, { id: 'mechanics' as const, name: 'Race Mechanics' }, { id: 'announcements' as const, name: 'Announcements' }, { id: 'faqs' as const, name: 'FAQs' }]), []);
  const canRegister = !unavailable.has(event.registration_availability); const registerHref = `/events/${event.id}/register`;
  async function copyLink() { await navigator.clipboard?.writeText(window.location.href); setCopied(true); window.setTimeout(() => setCopied(false), 1500); }
  const facebookUrl = safeSocialUrl(event.social_links?.facebook); const instagramUrl = safeSocialUrl(event.social_links?.instagram);
  return <main className="mx-auto max-w-7xl px-4 py-2 sm:px-6 sm:py-3"><div className="grid items-start gap-3 lg:grid-cols-[330px_minmax(0,1fr)]">
    <aside className="space-y-4 lg:sticky lg:top-6"><div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
      <section className="overflow-hidden bg-white"><div className="mx-auto mt-5 h-36 w-36 overflow-hidden rounded-2xl bg-slate-50"><EventLogo event={event} /></div><div className="space-y-3 p-5"><h1 className="text-xl font-bold leading-tight text-[#071b41]">{event.name}</h1>{event.tagline && event.tagline !== event.name && <p className="mt-2 text-sm italic text-slate-600">{event.tagline}</p>}<p className="text-sm text-slate-600"> <span className="ml-1">{dateFormat(event.event_date)}</span></p><p className="text-sm text-slate-600">Location: <span className="ml-1">{event.venue ?? event.address ?? 'Location to be announced'}</span></p><div className="border-t border-slate-100 pt-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Race Categories</p><div className="mt-3 flex flex-wrap gap-2">{event.categories.map((category) => <span key={category.id} className="rounded-full border border-orange-300 px-3 py-1 text-xs font-bold text-orange-600">{category.distance_km !== null ? `${category.distance_km}K` : category.name}</span>)}</div></div><div className="border-t border-slate-100 pt-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Share This Event</p><div className="mt-3 flex flex-wrap items-center gap-2"><button onClick={copyLink} className="grid h-8 w-8 place-items-center rounded-full bg-slate-100 text-sm" aria-label="Copy event link">Copy link</button>{copied && <span className="self-center text-xs text-emerald-600">Copied</span>}{facebookUrl && <a href={facebookUrl} target="_blank" rel="noreferrer" className="grid h-8 w-8 place-items-center rounded-full bg-[#1877f2] text-white transition hover:opacity-90" aria-label="Open Facebook page"><SocialIcon kind="facebook" /></a>}{instagramUrl && <a href={instagramUrl} target="_blank" rel="noreferrer" className="grid h-8 w-8 place-items-center rounded-full bg-gradient-to-br from-purple-600 via-pink-500 to-orange-400 text-white transition hover:opacity-90" aria-label="Open Instagram page"><SocialIcon kind="instagram" /></a>}</div></div></div></section>
      <section className="overflow-hidden border-t border-slate-100 bg-white"><div className="p-5"><div className="mt-4"><Countdown eventDate={event.event_date} startTime={event.start_time} /></div></div><div className="border-t border-slate-100 p-5">{canRegister ? <Link href={registerHref} className="block rounded-lg bg-orange-600 px-4 py-3 text-center text-sm font-bold text-white hover:bg-orange-700">Register Now</Link> : <span className="block rounded-lg bg-slate-200 px-4 py-3 text-center text-sm font-bold text-slate-500">Registration unavailable</span>}</div></section>
      </div>
      {event.partners.length > 0 && <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Event Partners</h2><div className="mt-4 space-y-4">{event.partners.map((partner) => <div key={partner.id}><p className="text-[9px] font-bold uppercase tracking-wider text-slate-500">{partner.partner_type ?? 'Partner'}</p><div className="mt-2 flex min-h-12 items-center justify-center rounded-lg border border-slate-100 p-2">{partner.logo_url ? <img src={partner.logo_url} alt={partner.name} className="max-h-10 max-w-full object-contain" /> : <span className="text-xs font-semibold text-slate-600">{partner.name}</span>}</div></div>)}</div></section>}
    </aside>
    <section className="min-w-0 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="aspect-[4/1] min-h-40 bg-slate-100">{event.banner_url ? <img src={event.banner_url} alt={`${event.name} banner`} className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center bg-[#071b41] text-2xl font-bold text-white">{event.name}</div>}</div><nav className="flex overflow-x-auto border-b border-slate-200 px-2 sm:px-4" aria-label="Event sections">{tabs.map((item) => <button key={item.id} onClick={() => setTab(item.id)} className={`whitespace-nowrap border-b-2 px-3 py-3 text-sm font-semibold ${tab === item.id ? 'border-orange-600 text-[#071b41]' : 'border-transparent text-slate-500 hover:text-[#071b41]'}`}>{item.name}</button>)}</nav><div className="p-2 sm:p-4">{tab === 'details' && <DetailsTab event={event} />}{tab === 'mechanics' && <MechanicsTab event={event} />}{tab === 'announcements' && <AnnouncementsTab event={event} />}{tab === 'faqs' && <FaqsTab />}</div></section>
  </div></main>;
}

function DetailsTab({ event }: { event: PublicEventDetails }) { const content = splitContent(event.description); return <section><div className="rounded-xl border border-slate-200 bg-white p-5 sm:p-7"><div className="max-w-4xl"><p className="whitespace-pre-wrap text-lg leading-8 text-slate-600">{content.description || 'Event details will be announced soon.'}</p></div>{event.content_images.length > 0 ? <div className="mt-6 grid grid-cols-1 gap-4">{event.content_images.map((image) => <img key={image.id} src={image.image_url} alt={`${event.name} poster`} className="block w-full rounded-lg object-contain" />)}</div> : <p className="mt-6 rounded-lg border border-dashed border-slate-300 p-6 text-center text-sm text-slate-500">No event posters available yet.</p>}</div></section>; }

function MechanicsTab({ event }: { event: PublicEventDetails }) { return <section className="space-y-7"><div><h2 className="text-2xl font-bold text-[#071b41]">Registration &amp; Race Mechanics</h2><div className="mt-4 overflow-x-auto rounded-xl border border-slate-200"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Category</th><th className="px-4 py-3">Fee</th><th className="px-4 py-3">Availability</th><th className="px-4 py-3">Start / Cut-off</th></tr></thead><tbody>{event.categories.map((category) => <tr key={category.id} className="border-t border-slate-100"><td className="px-4 py-4 font-semibold text-[#071b41]">{category.name}<span className="mt-1 block text-xs font-normal text-slate-500">{category.distance_km !== null ? `${category.distance_km} km` : 'Distance TBA'}</span></td><td className="px-4 py-4 font-semibold">{peso(category.registration_fee)}</td><td className="px-4 py-4 text-xs text-slate-600">{label(category.registration_availability)}</td><td className="px-4 py-4 text-xs text-slate-600">{category.gun_start_time ?? event.gun_start_time ?? 'TBA'} / {category.cutoff_time ?? event.cutoff_time ?? 'TBA'}</td></tr>)}</tbody></table></div></div>{event.routes.length > 0 && <div><h3 className="text-xl font-bold text-[#071b41]">Route Information</h3><div className="mt-4 grid gap-4 md:grid-cols-2">{event.routes.map((route) => <article key={route.id} className="rounded-xl border border-slate-200 p-4"><p className="font-semibold">{route.category_label ?? 'Event route'}</p>{route.description && <p className="mt-2 text-sm text-slate-600">{route.description}</p>}{route.route_map_url && <a href={route.route_map_url} target="_blank" rel="noreferrer" className="mt-3 inline-block text-sm font-semibold text-orange-600">View route map</a>}</article>)}</div></div>}</section>; }

function AnnouncementsTab({ event }: { event: PublicEventDetails }) { return <section><h2 className="text-2xl font-bold text-[#071b41]">Announcements</h2><div className="mt-5 space-y-4">{event.announcements.map((announcement) => <article key={announcement.id} className="rounded-xl border border-slate-200 p-5"><h3 className="font-bold text-[#071b41]">{announcement.title}</h3>{announcement.published_at && <p className="mt-1 text-xs text-slate-500">Published {dateTimeFormat(announcement.published_at)}</p>}<p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-600">{announcement.message}</p></article>)}</div></section>; }
function FaqsTab() { return <section className="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center"><h2 className="text-2xl font-bold text-[#071b41]">Frequently Asked Questions</h2><p className="mt-2 text-sm text-slate-600">Frequently asked questions will appear here when the organizer adds them.</p></section>; }
