'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import type { PublicEventDetails } from '@/lib/public/events';

type Tab = 'details' | 'mechanics' | 'announcements' | 'faqs';
const unavailable = new Set(['closed', 'sold_out', 'not_yet_open']);
const label = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
const dateFormat = (value: string) => { const date = new Date(value.includes('T') ? value : `${value}T00:00:00`); return Number.isNaN(date.getTime()) ? 'Date to be announced' : new Intl.DateTimeFormat('en-PH', { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' }).format(date); };
const dateTimeFormat = (value: string) => { const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Date to be announced' : new Intl.DateTimeFormat('en-PH', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' }).format(date); };
const peso = (value: number) => `PHP ${value.toLocaleString('en-PH', { minimumFractionDigits: 2 })}`;

function Countdown({ eventDate }: { eventDate: string }) {
  const [now, setNow] = useState(() => Date.now());
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 60_000); return () => window.clearInterval(timer); }, []);
  const target = new Date(`${eventDate}T23:59:59`).getTime(); const remaining = Number.isNaN(target) ? 0 : Math.max(0, target - now);
  const values = [Math.floor(remaining / 86_400_000), Math.floor((remaining / 3_600_000) % 24), Math.floor((remaining / 60_000) % 60)];
  return <div className="grid grid-cols-3 divide-x divide-slate-200 text-center">{values.map((value, index) => <div key={index}><p className="text-2xl font-bold text-[#071b41]">{value}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-wider text-slate-500">{['Days', 'Hrs', 'Mins'][index]}</p></div>)}</div>;
}

function splitContent(description: string | null) { const marker = /\nRace Mechanics\n/i; const parts = (description ?? '').split(marker); return { description: parts[0]?.trim() ?? '', mechanics: parts.slice(1).join('\nRace Mechanics\n').trim() }; }

function EventLogo({ event }: { event: PublicEventDetails }) { return event.logo_url ? <img src={event.logo_url} alt={`${event.name} logo`} className="h-full w-full object-contain" /> : event.banner_url ? <img src={event.banner_url} alt={`${event.name} thumbnail`} className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center bg-orange-50 text-4xl text-orange-500">Race</div>; }
function Status({ value }: { value: string }) { const styles = value === 'open' ? 'bg-emerald-50 text-emerald-700' : value === 'closed' || value === 'sold_out' ? 'bg-red-50 text-red-700' : 'bg-slate-100 text-slate-700'; return <span className={`inline-flex items-center gap-2 rounded-full px-3 py-1 text-xs font-bold ${styles}`}><span className="h-2 w-2 rounded-full bg-current" />{label(value)}</span>; }

export function EventDetailsClient({ event }: { event: PublicEventDetails }) {
  const [tab, setTab] = useState<Tab>('details'); const [copied, setCopied] = useState(false);
  const tabs = useMemo(() => ([{ id: 'details' as const, name: 'Event Details' }, { id: 'mechanics' as const, name: 'Race Mechanics' }, { id: 'announcements' as const, name: 'Announcements' }, { id: 'faqs' as const, name: 'FAQs' }]), []);
  const canRegister = !unavailable.has(event.registration_availability); const registerHref = `/events/${event.slug}/register`;
  async function copyLink() { await navigator.clipboard?.writeText(window.location.href); setCopied(true); window.setTimeout(() => setCopied(false), 1500); }
  return <main className="min-h-screen bg-[#f6f7fa] px-4 py-6 sm:px-6 lg:py-8"><div className="mx-auto grid max-w-7xl items-start gap-6 lg:grid-cols-[280px_minmax(0,1fr)]">
    <aside className="space-y-4 lg:sticky lg:top-6">
      <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="mx-auto mt-5 h-36 w-36 overflow-hidden rounded-2xl bg-slate-50"><EventLogo event={event} /></div><div className="space-y-3 p-5"><h1 className="text-xl font-bold leading-tight text-[#071b41]">{event.name}</h1>{event.tagline && event.tagline !== event.name && <p className="mt-2 text-sm italic text-slate-600">{event.tagline}</p>}<p className="text-sm text-slate-600"> <span className="ml-1">{dateFormat(event.event_date)}</span></p><p className="text-sm text-slate-600">Location: <span className="ml-1">{event.venue ?? event.address ?? 'Location to be announced'}</span></p><div className="border-t border-slate-100 pt-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Race Categories</p><div className="mt-3 flex flex-wrap gap-2">{event.categories.map((category) => <span key={category.id} className="rounded-full border border-orange-300 px-3 py-1 text-xs font-bold text-orange-600">{category.distance_km !== null ? `${category.distance_km}K` : category.name}</span>)}</div></div><div className="border-t border-slate-100 pt-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Share This Event</p><div className="mt-3 flex gap-2"><button onClick={copyLink} className="grid h-8 w-8 place-items-center rounded-full bg-slate-100 text-sm" aria-label="Copy event link">Copy link</button>{copied && <span className="self-center text-xs text-emerald-600">Copied</span>}</div></div></div></section>
      <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="p-5"><p className="text-center text-[10px] font-bold uppercase tracking-wider text-slate-500">Race Starts In</p><div className="mt-4"><Countdown eventDate={event.event_date} /></div></div><div className="border-t border-slate-100 p-5"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Registration Status</p><div className="mt-3"><Status value={event.registration_availability} /></div>{event.registration_opens_at && <p className="mt-3 text-xs text-slate-500">Opens {dateTimeFormat(event.registration_opens_at)}</p>}{event.registration_closes_at && <p className="mt-1 text-xs text-slate-500">Closes {dateTimeFormat(event.registration_closes_at)}</p>}{canRegister ? <Link href={registerHref} className="mt-4 block rounded-lg bg-orange-600 px-4 py-3 text-center text-sm font-bold text-white hover:bg-orange-700">Register Now</Link> : <span className="mt-4 block rounded-lg bg-slate-200 px-4 py-3 text-center text-sm font-bold text-slate-500">{label(event.registration_availability)}</span>}</div></section>
      {event.partners.length > 0 && <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Event Partners</h2><div className="mt-4 space-y-4">{event.partners.map((partner) => <div key={partner.id}><p className="text-[9px] font-bold uppercase tracking-wider text-slate-500">{partner.partner_type ?? 'Partner'}</p><div className="mt-2 flex min-h-12 items-center justify-center rounded-lg border border-slate-100 p-2">{partner.logo_url ? <img src={partner.logo_url} alt={partner.name} className="max-h-10 max-w-full object-contain" /> : <span className="text-xs font-semibold text-slate-600">{partner.name}</span>}</div></div>)}</div></section>}
    </aside>
    <section className="min-w-0 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="aspect-[4/1] min-h-40 bg-slate-100">{event.banner_url ? <img src={event.banner_url} alt={`${event.name} banner`} className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center bg-[#071b41] text-2xl font-bold text-white">{event.name}</div>}</div><nav className="flex overflow-x-auto border-b border-slate-200 px-4 sm:px-7" aria-label="Event sections">{tabs.map((item) => <button key={item.id} onClick={() => setTab(item.id)} className={`whitespace-nowrap border-b-2 px-4 py-4 text-sm font-semibold ${tab === item.id ? 'border-orange-600 text-[#071b41]' : 'border-transparent text-slate-500 hover:text-[#071b41]'}`}>{item.name}</button>)}</nav><div className="p-5 sm:p-8">{tab === 'details' && <DetailsTab event={event} />}{tab === 'mechanics' && <MechanicsTab event={event} />}{tab === 'announcements' && <AnnouncementsTab event={event} />}{tab === 'faqs' && <FaqsTab />}</div></section>
  </div></main>;
}

function DetailsTab({ event }: { event: PublicEventDetails }) { const content = splitContent(event.description); return <section><div className="rounded-xl border border-slate-200 bg-white p-5 sm:p-7"><div className="max-w-4xl"><p className="whitespace-pre-wrap text-lg leading-8 text-slate-600">{content.description || 'Event details will be announced soon.'}</p></div>{event.content_images.length > 0 ? <div className={`mt-6 grid gap-4 ${event.content_images.length === 1 ? 'mx-auto max-w-4xl' : 'sm:grid-cols-2'}`}>{event.content_images.map((image) => <img key={image.id} src={image.image_url} alt={`${event.name} poster`} className="w-full rounded-lg object-contain" />)}</div> : <p className="mt-6 rounded-lg border border-dashed border-slate-300 p-6 text-center text-sm text-slate-500">No event posters available yet.</p>}</div></section>; }

function MechanicsTab({ event }: { event: PublicEventDetails }) { return <section className="space-y-7"><div><h2 className="text-2xl font-bold text-[#071b41]">Registration &amp; Race Mechanics</h2><div className="mt-4 overflow-x-auto rounded-xl border border-slate-200"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Category</th><th className="px-4 py-3">Fee</th><th className="px-4 py-3">Availability</th><th className="px-4 py-3">Start / Cut-off</th></tr></thead><tbody>{event.categories.map((category) => <tr key={category.id} className="border-t border-slate-100"><td className="px-4 py-4 font-semibold text-[#071b41]">{category.name}<span className="mt-1 block text-xs font-normal text-slate-500">{category.distance_km !== null ? `${category.distance_km} km` : 'Distance TBA'}</span></td><td className="px-4 py-4 font-semibold">{peso(category.registration_fee)}</td><td className="px-4 py-4 text-xs text-slate-600">{label(category.registration_availability)}</td><td className="px-4 py-4 text-xs text-slate-600">{category.gun_start_time ?? event.gun_start_time ?? 'TBA'} / {category.cutoff_time ?? event.cutoff_time ?? 'TBA'}</td></tr>)}</tbody></table></div></div>{event.routes.length > 0 && <div><h3 className="text-xl font-bold text-[#071b41]">Route Information</h3><div className="mt-4 grid gap-4 md:grid-cols-2">{event.routes.map((route) => <article key={route.id} className="rounded-xl border border-slate-200 p-4"><p className="font-semibold">{route.category_label ?? 'Event route'}</p>{route.description && <p className="mt-2 text-sm text-slate-600">{route.description}</p>}{route.route_map_url && <a href={route.route_map_url} target="_blank" rel="noreferrer" className="mt-3 inline-block text-sm font-semibold text-orange-600">View route map</a>}</article>)}</div></div>}</section>; }

function AnnouncementsTab({ event }: { event: PublicEventDetails }) { return <section><h2 className="text-2xl font-bold text-[#071b41]">Announcements</h2><div className="mt-5 space-y-4">{event.announcements.map((announcement) => <article key={announcement.id} className="rounded-xl border border-slate-200 p-5"><h3 className="font-bold text-[#071b41]">{announcement.title}</h3>{announcement.published_at && <p className="mt-1 text-xs text-slate-500">Published {dateTimeFormat(announcement.published_at)}</p>}<p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-600">{announcement.message}</p></article>)}</div></section>; }
function FaqsTab() { return <section className="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center"><h2 className="text-2xl font-bold text-[#071b41]">Frequently Asked Questions</h2><p className="mt-2 text-sm text-slate-600">Frequently asked questions will appear here when the organizer adds them.</p></section>; }
