'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import type { PublicEventDetails } from '@/lib/public/events';

type Tab = 'details' | 'mechanics' | 'announcements' | 'results';
const unavailableStatuses = new Set(['closed', 'sold_out', 'not_yet_open']);
const label = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, item => item.toUpperCase());
const dateFormat = (value: string) => new Intl.DateTimeFormat('en-PH', { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value.includes('T') ? value : `${value}T00:00:00`));
const dateTimeFormat = (value: string) => new Intl.DateTimeFormat('en-PH', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(value));
const peso = (value: number) => `PHP ${value.toFixed(2)}`;

function Countdown({ eventDate }: { eventDate: string }) {
  const [now, setNow] = useState(() => Date.now());
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 60_000); return () => window.clearInterval(timer); }, []);
  const remaining = Math.max(0, new Date(`${eventDate}T23:59:59`).getTime() - now);
  const parts = { days: Math.floor(remaining / 86_400_000), hours: Math.floor((remaining / 3_600_000) % 24), mins: Math.floor((remaining / 60_000) % 60) };
  return <div className="grid grid-cols-3 divide-x divide-slate-200 text-center"><div><p className="text-2xl font-bold text-slate-900">{parts.days}</p><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Days</p></div><div><p className="text-2xl font-bold text-slate-900">{parts.hours}</p><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Hours</p></div><div><p className="text-2xl font-bold text-slate-900">{parts.mins}</p><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Mins</p></div></div>;
}

function EmptyVisual({ name }: { name: string }) { return <div className="grid h-full place-items-center bg-gradient-to-br from-slate-950 via-slate-800 to-orange-700 px-8 text-center text-2xl font-extrabold uppercase tracking-wide text-white">{name}</div>; }

export function EventDetailsClient({ event }: { event: PublicEventDetails }) {
  const [tab, setTab] = useState<Tab>('details');
  const unavailable = unavailableStatuses.has(event.registration_availability);
  const tabs = useMemo(() => ([
    { id: 'details' as const, name: 'Event Details' },
    { id: 'mechanics' as const, name: 'Race Mechanics' },
    ...(event.announcements.length ? [{ id: 'announcements' as const, name: 'Announcements' }] : []),
    ...(event.results_available ? [{ id: 'results' as const, name: 'Results' }] : []),
  ]), [event.announcements.length, event.results_available]);
  const registerHref = `/events/${event.slug}/register`;

  return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:py-8"><div className="grid items-start gap-6 lg:grid-cols-[260px_minmax(0,1fr)]">
    <aside className="space-y-5 lg:sticky lg:top-6">
      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="aspect-square bg-slate-100">{event.logo_url ? <img src={event.logo_url} alt={`${event.name} logo`} className="h-full w-full object-cover" /> : event.banner_url ? <img src={event.banner_url} alt="" className="h-full w-full object-cover" /> : <EmptyVisual name={event.name} />}</div><div className="space-y-3 p-5"><h1 className="text-xl font-bold leading-tight text-slate-900">{event.name}</h1><p className="text-sm text-slate-600">{dateFormat(event.event_date)}</p><p className="text-sm text-slate-600">{event.venue ?? event.address ?? 'Location to be announced'}</p></div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xs font-bold uppercase tracking-wide text-slate-500">Race Categories</h2><div className="mt-3 flex flex-wrap gap-2">{event.categories.map(category => <span key={category.id} className="rounded-full border border-orange-200 bg-orange-50 px-3 py-1 text-sm font-semibold text-orange-700">{category.distance_km !== null ? `${category.distance_km}K` : category.name}</span>)}</div></section>
      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="p-5"><p className="text-center text-xs font-bold uppercase tracking-wide text-slate-500">Race starts in</p><div className="mt-4"><Countdown eventDate={event.event_date} /></div></div><div className="border-t border-slate-100 p-5"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Registration Status</p><p className={`mt-2 inline-flex rounded-full px-3 py-1 text-sm font-semibold ${event.registration_availability === 'open' ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-700'}`}>{label(event.registration_availability)}</p>{event.registration_closes_at && <p className="mt-3 text-xs text-slate-500">Closes {dateTimeFormat(event.registration_closes_at)}</p>}{!unavailable && <Link href={registerHref} className="mt-4 block rounded-xl bg-orange-600 px-4 py-3 text-center text-sm font-bold text-white transition hover:bg-orange-700">Register Now</Link>}</div></section>
      {event.partners.length > 0 && <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xs font-bold uppercase tracking-wide text-slate-500">Event Partners</h2><div className="mt-4 grid grid-cols-2 gap-3">{event.partners.map(partner => <div key={partner.id} className="grid min-h-14 place-items-center rounded-lg border border-slate-100 p-2 text-center text-xs font-semibold text-slate-600">{partner.logo_url ? <img src={partner.logo_url} alt={partner.name} className="max-h-10 max-w-full object-contain" /> : partner.name}</div>)}</div></section>}
    </aside>
    <section className="min-w-0 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="relative h-64 bg-slate-900 sm:h-80">{event.banner_url ? <img src={event.banner_url} alt={`${event.name} banner`} className="h-full w-full object-cover" /> : <EmptyVisual name={event.name} />}<div className="absolute inset-0 bg-gradient-to-r from-slate-950/85 via-slate-950/25 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-6 text-white sm:p-8"><p className="text-sm font-semibold text-orange-200">{event.organizer?.name ?? 'RaceDeck event'}</p><h2 className="mt-1 max-w-3xl text-3xl font-extrabold tracking-tight sm:text-5xl">{event.name}</h2><p className="mt-3 text-sm text-slate-100 sm:text-base">{dateFormat(event.event_date)} <span className="mx-2">•</span> {event.venue ?? event.address ?? 'Location to be announced'}</p></div></div>
      <div className="flex overflow-x-auto border-b border-slate-200 px-4 sm:px-6">{tabs.map(item => <button key={item.id} onClick={() => setTab(item.id)} className={`whitespace-nowrap border-b-2 px-4 py-4 text-sm font-semibold ${tab === item.id ? 'border-orange-600 text-slate-900' : 'border-transparent text-slate-500 hover:text-slate-900'}`}>{item.name}</button>)}</div>
      <div className="p-5 sm:p-8">{tab === 'details' && <section className="space-y-8"><div className="mx-auto max-w-3xl text-center"><h2 className="text-2xl font-bold text-slate-900">Welcome to {event.name}</h2><p className="mt-3 whitespace-pre-wrap leading-7 text-slate-600">{event.description ?? 'Event details will be announced soon.'}</p></div><div className="grid gap-3 rounded-2xl bg-slate-50 p-5 text-sm sm:grid-cols-2"><p><span className="font-semibold text-slate-900">Event date:</span> {dateFormat(event.event_date)}</p><p><span className="font-semibold text-slate-900">Venue:</span> {event.venue ?? event.address ?? 'TBA'}</p><p><span className="font-semibold text-slate-900">Assembly:</span> {event.assembly_time ?? 'TBA'}</p><p><span className="font-semibold text-slate-900">Gun start:</span> {event.gun_start_time ?? event.start_time ?? 'TBA'}</p><p><span className="font-semibold text-slate-900">Cut-off:</span> {event.cutoff_time ?? 'TBA'}</p><p><span className="font-semibold text-slate-900">Organizer:</span> {event.organizer_details?.name ?? event.organizer?.name ?? 'TBA'}</p></div>{event.schedules.length > 0 && <div><h3 className="text-xl font-bold text-slate-900">Event Schedule</h3><div className="mt-4 space-y-3">{event.schedules.map(schedule => <article key={schedule.id} className="rounded-xl border border-slate-200 p-4"><p className="font-semibold text-slate-900">{schedule.label}</p><p className="mt-1 text-sm text-slate-600">{dateTimeFormat(schedule.scheduled_at)}</p>{schedule.notes && <p className="mt-2 text-sm text-slate-600">{schedule.notes}</p>}</article>)}</div></div>}</section>}
        {tab === 'mechanics' && <section className="space-y-8"><div><h2 className="text-2xl font-bold text-slate-900">Registration &amp; Race Categories</h2><div className="mt-4 overflow-x-auto rounded-2xl border border-slate-200"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Category</th><th className="px-4 py-3">Registration Fee</th><th className="px-4 py-3">Availability</th><th className="px-4 py-3">Start / Cut-off</th></tr></thead><tbody>{event.categories.map(category => <tr key={category.id} className="border-t border-slate-100"><td className="px-4 py-4 font-semibold text-slate-900">{category.name}<span className="mt-1 block text-xs font-normal text-slate-500">{category.distance_km !== null ? `${category.distance_km} km` : 'Distance TBA'}</span></td><td className="px-4 py-4 font-semibold">{peso(category.registration_fee)}</td><td className="px-4 py-4"><span className="text-xs font-semibold text-slate-600">{label(category.registration_availability)}</span><span className="mt-1 block text-xs text-slate-500">{category.available_slots === null ? 'Slots available' : `${category.available_slots} slots available`}</span></td><td className="px-4 py-4 text-xs text-slate-600">{category.gun_start_time ?? event.gun_start_time ?? 'TBA'}<br />{category.cutoff_time ?? event.cutoff_time ?? 'TBA'}</td></tr>)}</tbody></table></div></div>{event.routes.length > 0 && <div><h3 className="text-xl font-bold text-slate-900">Route Information</h3><div className="mt-4 grid gap-4 md:grid-cols-2">{event.routes.map(route => <article key={route.id} className="rounded-2xl border border-slate-200 p-5"><p className="font-semibold text-slate-900">{route.category_label ?? 'Event route'}</p><p className="mt-2 text-sm text-slate-600">{route.starting_point ?? 'Start TBA'} → {route.finish_point ?? 'Finish TBA'}</p>{route.description && <p className="mt-2 text-sm text-slate-600">{route.description}</p>}{route.route_map_url && <a href={route.route_map_url} target="_blank" rel="noreferrer" className="mt-3 inline-block text-sm font-semibold text-orange-600 hover:text-orange-700">View route map →</a>}</article>)}</div></div>}{event.kits.length > 0 && <div><h3 className="text-xl font-bold text-slate-900">Race Kit Inclusions</h3><div className="mt-4 grid gap-4 md:grid-cols-2">{event.kits.map(kit => <article key={kit.id} className="rounded-2xl bg-slate-50 p-5"><p className="font-semibold text-slate-900">{kit.name}</p><p className="mt-1 text-sm text-slate-600">{kit.category_id ? event.categories.find(category => category.id === kit.category_id)?.name ?? 'Selected category' : 'All categories'}</p>{kit.description && <p className="mt-2 text-sm text-slate-600">{kit.description}</p>}<ul className="mt-3 space-y-1 text-sm text-slate-700">{kit.items.map(item => <li key={item.id}>• {item.item_name} × {item.quantity}</li>)}</ul></article>)}</div></div>}</section>}
        {tab === 'announcements' && <section><h2 className="text-2xl font-bold text-slate-900">Announcements</h2><div className="mt-5 space-y-4">{event.announcements.map(announcement => <article key={announcement.id} className="rounded-2xl border border-slate-200 p-5"><h3 className="font-bold text-slate-900">{announcement.title}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{announcement.message}</p>{announcement.published_at && <p className="mt-3 text-xs text-slate-500">Published {dateTimeFormat(announcement.published_at)}</p>}</article>)}</div></section>}
        {tab === 'results' && <section className="text-center"><h2 className="text-2xl font-bold text-slate-900">Results are available</h2><p className="mx-auto mt-3 max-w-xl text-slate-600">View published results for this event.</p><Link href={`/results?event=${encodeURIComponent(event.id)}`} className="mt-5 inline-block rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white">View Results</Link></section>}</div>
    </section>
  </div>{!unavailable && <div className="fixed inset-x-0 bottom-0 z-20 border-t border-slate-200 bg-white/95 p-3 backdrop-blur lg:hidden"><Link href={registerHref} className="mx-auto block max-w-lg rounded-xl bg-orange-600 px-4 py-3 text-center text-sm font-bold text-white">Register Now</Link></div>}</main>;
}
