import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { authenticatedClient } from './helpers/auth';
import { cleanupLocalFixture, seedLocalFixture, seedSecondOrganization } from './helpers/supabase';

describe('RaceDeck local Supabase integration contracts', () => { let fixture: Awaited<ReturnType<typeof seedLocalFixture>>;
  beforeAll(async () => { fixture = await seedLocalFixture(); }); afterAll(async () => { if (fixture) await cleanupLocalFixture(fixture); });
  it('separates upload_results from publish_results permission', async () => { const { data: upload } = await fixture.admin.from('permissions').select('id').eq('key', 'upload_results').single(); const { data: publish } = await fixture.admin.from('permissions').select('id').eq('key', 'publish_results').single(); expect(upload?.id).toBeTruthy(); expect(publish?.id).toBeTruthy(); const { data: original } = await fixture.admin.from('role_permissions').select('role,permission_id').eq('role', 'results_staff'); try { await fixture.admin.from('role_permissions').delete().eq('role', 'results_staff'); await fixture.admin.from('role_permissions').insert({ role: 'results_staff', permission_id: upload!.id }); const { data: assigned } = await fixture.admin.from('role_permissions').select('permission_id').eq('role', 'results_staff'); expect(assigned?.map((row) => row.permission_id)).toEqual([upload!.id]); } finally { await fixture.admin.from('role_permissions').delete().eq('role', 'results_staff'); if (original?.length) await fixture.admin.from('role_permissions').insert(original); } });
  it('does not allow Organization B to modify Organization A events', async () => { const second = await seedSecondOrganization(fixture.admin); try { const client = await authenticatedClient(second.user); const { data } = await client.from('events').update({ name: 'cross-tenant mutation' }).eq('id', fixture.event.id).select('id'); expect(data).toEqual([]); } finally { await fixture.admin.from('organizations').delete().eq('id', second.organization.id); await fixture.admin.auth.admin.deleteUser(second.user.id); } });
  it('preserves published batch idempotency contract', async () => { const { data: batches } = await fixture.admin.from('result_batches').select('id,publication_status').eq('event_id', fixture.event.id); expect(batches ?? []).toEqual([]); expect((batches ?? []).filter((row) => row.publication_status === 'published')).toHaveLength(0); });
  it('supports draft supersede columns without changing published state model', async () => { const { data } = await fixture.admin.from('result_batches').select('is_superseded,superseded_by_batch_id').eq('event_id', fixture.event.id); expect(data).toEqual([]); });
  it('scopes participant registrations to the authenticated user', async () => { const client = await authenticatedClient(fixture.participant); const { data } = await client.from('registrations').select('id').eq('id', fixture.registration.id).eq('user_id', fixture.participant.id); expect(data).toHaveLength(1); });
  it('does not return payment rows for a participant without that registration', async () => { const client = await authenticatedClient(fixture.participant); const { data } = await client.from('payments').select('id').eq('registration_id', '00000000-0000-0000-0000-000000000000'); expect(data).toEqual([]); });
  it('requires local-only credentials for integration setup', () => { expect(process.env.NEXT_PUBLIC_SUPABASE_URL).toMatch(/127\.0\.0\.1|localhost/); expect(process.env.SUPABASE_SERVICE_ROLE_KEY).toBeTruthy(); });
});
