import { NextResponse } from 'next/server';
import { z } from 'zod';
import { hasPermission, loadAuthContext } from '@/lib/auth/permissions';
import { createAdminClient } from '@/lib/supabase/admin';
import { verifyRegistrationToken } from '@/lib/qr/qr.service';

const lookupInput = z.object({ action: z.literal('lookup'), registration_id: z.string().uuid().optional(), qr_value: z.string().trim().min(1).max(2000).optional(), participant_query: z.string().trim().min(2).max(120).optional() }).refine((value) => value.registration_id || value.qr_value || value.participant_query, { message: 'Provide a registration ID, QR value, or participant search.' });
const claimInput = z.object({ action: z.literal('claim'), registration_id: z.string().uuid(), claim_method: z.enum(['qr_scan', 'manual_lookup']), scan_reference: z.string().trim().max(2000).nullable().optional(), qr_value: z.string().trim().max(2000).optional() });
const input = z.discriminatedUnion('action', [lookupInput, claimInput]);

async function authorize(eventId: string) {
  const context = await loadAuthContext(); if (!context) return { response: NextResponse.json({ error: 'Authentication required' }, { status: 401 }) } as const;
  const internalAdmin = context.internalRoles.includes('admin') || context.internalRoles.includes('super_admin'); let membership = context.memberships[0]; for (const item of context.memberships) { if (await hasPermission(item.organization_id, 'scan_race_kits', eventId)) { membership = item; break; } }
  if (!internalAdmin && (!membership || !(await hasPermission(membership.organization_id, 'scan_race_kits', eventId)))) return { response: NextResponse.json({ error: 'Race-kit claiming permission required' }, { status: 403 }) } as const;
  const admin = createAdminClient(); let query = admin.from('events').select('id,organization_id').eq('id', eventId); if (membership && !internalAdmin) query = query.eq('organization_id', membership.organization_id); const { data: event } = await query.maybeSingle(); if (!event) return { response: NextResponse.json({ error: 'Event not found' }, { status: 404 }) } as const;
  return { context, event, admin } as const;
}

function qrPayload(value: string) { try { const parsed = JSON.parse(value) as { registration_id?: string; token?: string }; if (parsed.registration_id && parsed.token) return parsed; } catch { return null; } return null; }

async function loadClaimView(admin: ReturnType<typeof createAdminClient>, eventId: string, registrationId: string, qrToken?: string) {
  if (qrToken) { const payload = qrPayload(qrToken); if (!payload || payload.registration_id !== registrationId || !verifyRegistrationToken(registrationId, payload.token ?? '')) return { error: 'Invalid registration QR' } as const; }
  const { data: registration, error } = await admin.from('registrations').select('id,registration_number,event_id,category_id,status,first_name,last_name,email,bib_id,race_categories(id,name),payments(status,paid_at),bibs(id,bib_number,bib_code,status)').eq('id', registrationId).eq('event_id', eventId).maybeSingle(); if (error || !registration) return { error: 'Registration was not found for this event' } as const;
  const category = Array.isArray(registration.race_categories) ? registration.race_categories[0] : registration.race_categories; const bib = Array.isArray(registration.bibs) ? registration.bibs.find((item) => item.status === 'active') : registration.bibs; const payment = Array.isArray(registration.payments) ? registration.payments[0] : registration.payments;
  const { data: specific } = category ? await admin.from('race_kit_configs').select('id,name,description,status,category_id,race_kit_items(id,item_code,item_name,quantity,details,is_required,is_active,display_order)').eq('event_id', eventId).eq('category_id', category.id).eq('status', 'active').maybeSingle() : { data: null }; const { data: fallback } = !specific ? await admin.from('race_kit_configs').select('id,name,description,status,category_id,race_kit_items(id,item_code,item_name,quantity,details,is_required,is_active,display_order)').eq('event_id', eventId).is('category_id', null).eq('status', 'active').maybeSingle() : { data: null }; const kit = specific ?? fallback;
  const { data: claim } = await admin.from('race_kit_claims').select('id,claimed_at,claimed_by,claim_method,scan_reference,config_id').eq('registration_id', registrationId).maybeSingle();
  return { registration, category, bib, payment, kit, claim } as const;
}

export async function POST(request: Request, { params }: { params: { eventId: string } }) {
  const auth = await authorize(params.eventId); if ('response' in auth) return auth.response; const parsed = input.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message ?? 'Invalid race-kit request' }, { status: 400 });
  if (parsed.data.action === 'lookup') {
    let registrationId = parsed.data.registration_id; let qrToken: string | undefined;
    if (parsed.data.qr_value) { const payload = qrPayload(parsed.data.qr_value); if (!payload || !verifyRegistrationToken(payload.registration_id ?? '', payload.token ?? '')) return NextResponse.json({ error: 'Invalid registration QR' }, { status: 400 }); registrationId = payload.registration_id; qrToken = parsed.data.qr_value; }
    if (!registrationId && parsed.data.participant_query) { const safe = parsed.data.participant_query.replace(/[(),]/g, ' '); const { data: matches } = await auth.admin.from('registrations').select('id,registration_number,first_name,last_name,status,category_id,race_categories(name)').eq('event_id', params.eventId).or(`registration_number.ilike.%${safe}%,first_name.ilike.%${safe}%,last_name.ilike.%${safe}%`).order('registration_number').limit(20); return NextResponse.json({ matches: matches ?? [] }); }
    if (!registrationId) return NextResponse.json({ error: 'Registration could not be resolved' }, { status: 400 }); const view = await loadClaimView(auth.admin, params.eventId, registrationId, qrToken); if ('error' in view) return NextResponse.json({ error: view.error }, { status: 404 }); return NextResponse.json({ ...view, claim_allowed: view.registration.status === 'confirmed' && view.payment?.status === 'succeeded' && !!view.bib && !!view.kit && !view.claim });
  }
  const qrToken = parsed.data.qr_value; const view = await loadClaimView(auth.admin, params.eventId, parsed.data.registration_id, qrToken); if ('error' in view) return NextResponse.json({ error: view.error }, { status: 400 }); const { registration, category, bib, payment, kit, claim } = view;
  if (claim) { await auth.admin.from('audit_logs').insert({ actor_user_id: auth.context.user.id, organization_id: auth.event.organization_id, event_id: params.eventId, action: 'race_kit_claim_duplicate_rejected', resource_type: 'race_kit_claim', resource_id: claim.id, metadata: { registration_id: registration.id } }); return NextResponse.json({ error: 'Race kit has already been claimed', claim }, { status: 409 }); }
  if (registration.status !== 'confirmed') return NextResponse.json({ error: 'Only confirmed registrations may claim race kits' }, { status: 409 }); if (payment?.status !== 'succeeded') return NextResponse.json({ error: 'A successful payment is required before claiming' }, { status: 409 }); if (!category || !bib || bib.status !== 'active') return NextResponse.json({ error: 'An active bib is required before claiming' }, { status: 409 }); if (!kit) return NextResponse.json({ error: 'No active race-kit configuration exists for this category' }, { status: 409 });
  const claimReference = parsed.data.claim_method === 'qr_scan' ? (parsed.data.scan_reference ?? qrToken ?? null) : (parsed.data.scan_reference ?? registration.registration_number); if (!claimReference) return NextResponse.json({ error: 'A QR scan reference is required' }, { status: 400 }); const { data: created, error } = await auth.admin.from('race_kit_claims').insert({ registration_id: registration.id, event_id: params.eventId, category_id: category.id, bib_id: bib.id, config_id: kit.id, claimed_by: auth.context.user.id, claim_method: parsed.data.claim_method, scan_reference: claimReference, metadata: { source: 'race_kit_claiming' } }).select('id,claimed_at,claimed_by,claim_method,config_id').single(); if (error || !created) { if (error?.code === '23505') return NextResponse.json({ error: 'Race kit has already been claimed' }, { status: 409 }); return NextResponse.json({ error: 'Race kit could not be claimed' }, { status: 500 }); }
  await Promise.all([auth.admin.from('registration_activity').insert({ registration_id: registration.id, action: 'kit_claimed', actor: auth.context.user.id, metadata: { claim_id: created.id, bib_id: bib.id, config_id: kit.id } }), auth.admin.from('audit_logs').insert({ actor_user_id: auth.context.user.id, organization_id: auth.event.organization_id, event_id: params.eventId, action: 'race_kit_claimed', resource_type: 'race_kit_claim', resource_id: created.id, new_values: { registration_id: registration.id, bib_id: bib.id, config_id: kit.id, claim_method: parsed.data.claim_method } })]); return NextResponse.json({ claim: created, registration, category, bib, payment, kit }, { status: 201 });
}
