import { NextResponse } from 'next/server';
import { z } from 'zod';
import { hasPermission, loadAuthContext } from '@/lib/auth/permissions';
import { createAdminClient } from '@/lib/supabase/admin';
import { createClient } from '@/lib/supabase/server';
import type { Database } from '@/types/database.types';
/* The parsed category list is validated separately before settings are persisted. */
/* eslint-disable @typescript-eslint/no-unused-vars */

const schema = z.object({
  enabled: z.boolean(), template_id: z.string().uuid().nullable(), certificate_title: z.string().trim().max(240).nullable(),
  event_logo_reference: z.string().trim().max(1000).nullable(), organizer_logo_reference: z.string().trim().max(1000).nullable(), sponsor_logo_config: z.array(z.unknown()), signature_image_reference: z.string().trim().max(1000).nullable(), signatory_name: z.string().trim().max(200).nullable(), signatory_position: z.string().trim().max(200).nullable(), certificate_message: z.string().trim().max(4000).nullable(), eligibility_mode: z.enum(['finished_all', 'finished_selected_categories', 'organizer_defined']), category_ids: z.array(z.string().uuid()).max(100),
});
type SettingsInsert = Database['public']['Tables']['event_certificate_settings']['Insert'];
async function authorize(eventId: string) { const context = await loadAuthContext(); if (!context) return { response: NextResponse.json({ error: 'Authentication required' }, { status: 401 }) } as const; const membership = context.memberships[0]; if (!membership || !(await hasPermission(membership.organization_id, 'manage_certificates', eventId))) return { response: NextResponse.json({ error: 'Certificate permission required' }, { status: 403 }) } as const; const supabase = await createClient(); const { data: event } = await supabase.from('events').select('id,organization_id,name,event_date').eq('id', eventId).eq('organization_id', membership.organization_id).maybeSingle(); if (!event) return { response: NextResponse.json({ error: 'Event not found' }, { status: 404 }) } as const; return { context, event } as const; }
export async function GET(_request: Request, { params }: { params: { eventId: string } }) { const result = await authorize(params.eventId); if ('response' in result) return result.response; const admin = createAdminClient(); const [{ data: settings }, { data: categories }, { data: templates, error }] = await Promise.all([admin.from('event_certificate_settings').select('id,event_id,organization_id,enabled,template_id,certificate_title,event_logo_reference,organizer_logo_reference,sponsor_logo_config,signature_image_reference,signatory_name,signatory_position,certificate_message,eligibility_mode,created_at,updated_at,event_certificate_categories(race_category_id)').eq('event_id', params.eventId).eq('organization_id', result.event.organization_id).maybeSingle(), admin.from('race_categories').select('id,name').eq('event_id', params.eventId).order('name'), admin.from('certificate_templates').select('id,name,certificate_title,version,status,is_system_template,organization_id').eq('status', 'active').or(`is_system_template.eq.true,organization_id.eq.${result.event.organization_id}`).order('name')]); if (error) { console.error('Unable to load certificate templates', error); return NextResponse.json({ error: 'Certificate settings could not be loaded' }, { status: 500 }); } return NextResponse.json({ event: { name: result.event.name, event_date: result.event.event_date }, settings: settings ? { ...settings, category_ids: settings.event_certificate_categories.map(item => item.race_category_id) } : null, categories: categories ?? [], templates: templates ?? [] }); }
export async function POST(request: Request, { params }: { params: { eventId: string } }) { const result = await authorize(params.eventId); if ('response' in result) return result.response; const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: 'Invalid certificate settings' }, { status: 400 }); const categoryIds = parsed.data.category_ids.filter((id, index, all) => all.indexOf(id) === index); if (parsed.data.eligibility_mode === 'finished_selected_categories' && categoryIds.length === 0) return NextResponse.json({ error: 'Select at least one eligible category' }, { status: 400 }); const admin = createAdminClient(); if (categoryIds.length) { const { count } = await admin.from('race_categories').select('id', { count: 'exact', head: true }).eq('event_id', params.eventId).in('id', categoryIds); if (count !== categoryIds.length) return NextResponse.json({ error: 'One or more categories do not belong to this event' }, { status: 400 }); } if (parsed.data.template_id) { const { data: template } = await admin.from('certificate_templates').select('id').eq('id', parsed.data.template_id).eq('status', 'active').or(`is_system_template.eq.true,organization_id.eq.${result.event.organization_id}`).maybeSingle(); if (!template) return NextResponse.json({ error: 'Template is not available for this organization' }, { status: 400 }); } const { category_ids: _categoryIds, ...rawSettings } = parsed.data; const settings = rawSettings as SettingsInsert; const { data, error } = await admin.from('event_certificate_settings').upsert({ ...settings, event_id: params.eventId, organization_id: result.event.organization_id }, { onConflict: 'event_id' }).select('*').single(); if (error) { console.error('Unable to save certificate settings', error); return NextResponse.json({ error: 'Certificate settings could not be saved' }, { status: 500 }); } await admin.from('event_certificate_categories').delete().eq('settings_id', data.id); if (categoryIds.length) { const { error: categoryError } = await admin.from('event_certificate_categories').insert(categoryIds.map(race_category_id => ({ settings_id: data.id, race_category_id }))); if (categoryError) { console.error('Unable to save certificate categories', categoryError); return NextResponse.json({ error: 'Certificate category settings could not be saved' }, { status: 500 }); } } return NextResponse.json(data); }
