'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';

type Waiver = { id: string; title: string; version: number; content: string | null; status: 'draft' | 'published' | 'retired'; effective_at: string; created_at: string; updated_at: string; acceptance_count: number };

export default function OrganizerWaiverPage({ params }: { params: { eventId: string } }) {
  const [waivers, setWaivers] = useState<Waiver[]>([]); const [selected, setSelected] = useState<Waiver | null>(null); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [message, setMessage] = useState('Loading waiver…'); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const response = await fetch(`/api/organizer/events/${params.eventId}/waiver`); const data = await response.json().catch(() => ({})); if (!response.ok) { setMessage(data.error ?? 'Waiver could not be loaded.'); return; } setWaivers(data.waivers ?? []); const current = (data.waivers ?? []).find((waiver: Waiver) => waiver.status === 'published') ?? data.waivers?.[0] ?? null; setSelected(current); setTitle(current?.title ?? ''); setContent(current?.content ?? ''); setMessage(''); }, [params.eventId]);
  useEffect(() => { void load(); }, [load]);
  function newVersion() { setSelected(null); setTitle(''); setContent(''); setMessage('Creating a new waiver version.'); }
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); const response = await fetch(`/api/organizer/events/${params.eventId}/waiver${selected ? '' : ''}`, { method: selected ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(selected ? { id: selected.id, title, content } : { title, content }) }); const data = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) { setMessage(data.error ?? 'Waiver could not be saved.'); return; } setMessage('Waiver saved as a draft.'); await load(); }
  async function activate() { if (!selected || selected.status !== 'draft' || !window.confirm('Activate this waiver version for future registrations?')) return; setBusy(true); const response = await fetch(`/api/organizer/events/${params.eventId}/waiver`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: selected.id, action: 'publish' }) }); const data = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) { setMessage(data.error ?? 'Waiver could not be activated.'); return; } setMessage('Waiver activated.'); await load(); }
  return <main className="mx-auto max-w-4xl space-y-6 p-6"><header><h1 className="text-2xl font-semibold">Event Waiver</h1><p className="text-sm text-gray-600">Configure the waiver participants must accept during registration.</p></header>{message && <p role="status" className="text-sm">{message}</p>}<section className="rounded border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Current waiver</h2><p className="text-sm text-gray-600">{selected ? `Version ${selected.version} · ${selected.status} · ${selected.acceptance_count} acceptance${selected.acceptance_count === 1 ? '' : 's'}` : 'No waiver configured'}</p></div><button onClick={newVersion} className="rounded border px-3 py-2 text-sm">{waivers.length ? 'Create New Version' : 'Create Waiver'}</button></div>{selected?.acceptance_count ? <p className="mt-3 rounded bg-amber-50 p-3 text-sm">This waiver version has already been accepted by participants. Its legal content is preserved; create a new version to change it.</p> : null}</section><form onSubmit={save} className="space-y-4 rounded border p-4"><label className="block text-sm">Waiver Title<input required maxLength={240} value={title} onChange={event => setTitle(event.target.value)} className="mt-1 w-full rounded border p-2" /></label><label className="block text-sm">Waiver Content<textarea required value={content} onChange={event => setContent(event.target.value)} rows={12} className="mt-1 w-full rounded border p-2" /></label><div className="flex gap-2"><button disabled={busy || (selected?.status !== 'draft' && !!selected)} className="rounded bg-black px-3 py-2 text-sm text-white">{busy ? 'Saving…' : 'Save Draft'}</button>{selected?.status === 'draft' && <button type="button" disabled={busy} onClick={activate} className="rounded border px-3 py-2 text-sm">Activate Current Version</button>}</div></form><section className="rounded border p-4"><h2 className="font-semibold">Waiver history</h2><div className="mt-2 space-y-2">{waivers.length ? waivers.map(waiver => <button key={waiver.id} onClick={() => { setSelected(waiver); setTitle(waiver.title); setContent(waiver.content ?? ''); setMessage(''); }} className="block w-full rounded border p-3 text-left text-sm">Version {waiver.version} · {waiver.status} · {waiver.acceptance_count} acceptance{waiver.acceptance_count === 1 ? '' : 's'}</button>) : <p className="text-sm text-gray-600">No waiver versions yet.</p>}</div></section></main>;
}
