'use client';

import { useEffect, useRef, useState } from 'react';

type Announcement = { id: string; title: string; message: string; audience: 'all_confirmed' | 'category_confirmed'; race_category_id: string | null; delivery_channels: Array<'in_app' | 'email'>; status: string; sent_at: string | null; created_at: string; race_categories: { id: string; name: string } | { id: string; name: string }[] | null };
type Category = { id: string; name: string };

export default function AnnouncementsPage({ params }: { params: { eventId: string } }) {
  const [items, setItems] = useState<Announcement[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [title, setTitle] = useState(''); const [message, setMessage] = useState(''); const [audience, setAudience] = useState<'all_confirmed' | 'category_confirmed'>('all_confirmed'); const [categoryId, setCategoryId] = useState(''); const [inApp, setInApp] = useState(true); const [email, setEmail] = useState(false); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('Loading announcements…'); const submissionKey = useRef<string | null>(null);
  async function load() { const [announcementResponse, categoryResponse] = await Promise.all([fetch(`/api/organizer/events/${params.eventId}/announcements`), fetch(`/api/organizer/events/${params.eventId}/categories`)]); const announcementBody = await announcementResponse.json().catch(() => ({})); if (!announcementResponse.ok) { setNotice(announcementBody.error ?? 'Announcements could not be loaded.'); return; } setItems(announcementBody.announcements ?? []); if (categoryResponse.ok) setCategories((await categoryResponse.json()).map((item: Category) => ({ id: item.id, name: item.name }))); setNotice(''); }
  // The loader is scoped to this event page.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load(); }, [params.eventId]);
  async function send() { if (!title.trim() || !message.trim() || (!inApp && !email) || (audience === 'category_confirmed' && !categoryId)) { setNotice('Complete the title, message, audience, category, and at least one channel.'); return; } setBusy(true); const idempotencyKey = submissionKey.current ?? crypto.randomUUID(); submissionKey.current = idempotencyKey; const response = await fetch(`/api/organizer/events/${params.eventId}/announcements`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title, message, audience, race_category_id: audience === 'category_confirmed' ? categoryId : null, delivery_channels: [inApp ? 'in_app' : null, email ? 'email' : null].filter(Boolean), idempotency_key: idempotencyKey }) }); const body = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) { setNotice(body.error ?? 'Announcement could not be sent.'); return; } submissionKey.current = null; setTitle(''); setMessage(''); setNotice(`Announcement queued for ${body.recipient_count ?? 0} confirmed participant(s).`); await load(); }
  return <main className="mx-auto max-w-6xl space-y-6 p-6"><header><h1 className="text-2xl font-semibold">Announcements</h1><p className="text-sm text-gray-600">Send event updates to confirmed participants.</p></header><section className="space-y-3 rounded border p-4"><h2 className="font-semibold">Create Announcement</h2><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Title / subject" className="w-full rounded border p-2" /><textarea value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Message" className="min-h-32 w-full rounded border p-2" /><div className="grid gap-3 md:grid-cols-2"><label className="text-sm">Audience<select value={audience} onChange={(e) => { const value = e.target.value as typeof audience; setAudience(value); if (value === 'all_confirmed') setCategoryId(''); }} className="mt-1 w-full rounded border p-2"><option value="all_confirmed">All confirmed participants</option><option value="category_confirmed">Selected category</option></select></label>{audience === 'category_confirmed' && <label className="text-sm">Race Category<select required value={categoryId} onChange={(e) => setCategoryId(e.target.value)} className="mt-1 w-full rounded border p-2"><option value="">Select category</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label>}</div><div className="flex gap-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={inApp} onChange={(e) => setInApp(e.target.checked)} />In-App</label><label className="flex items-center gap-2"><input type="checkbox" checked={email} onChange={(e) => setEmail(e.target.checked)} />Email</label></div><button disabled={busy} onClick={() => void send()} className="rounded bg-black px-4 py-2 text-sm text-white">{busy ? 'Sending…' : 'Send Announcement'}</button></section>{notice && <p role="status" className="text-sm">{notice}</p>}{items.length === 0 && !notice ? <p className="rounded border p-4 text-sm">No announcements yet.</p> : <div className="overflow-x-auto rounded border"><table className="w-full text-left text-sm"><thead className="border-b bg-gray-50"><tr><th className="p-3">Title</th><th className="p-3">Audience</th><th className="p-3">Channels</th><th className="p-3">Created</th><th className="p-3">Delivery Status</th></tr></thead><tbody>{items.map((item) => { const category = Array.isArray(item.race_categories) ? item.race_categories[0] : item.race_categories; return <tr key={item.id} className="border-b last:border-0"><td className="p-3 font-medium">{item.title}</td><td className="p-3">{item.audience === 'all_confirmed' ? 'All confirmed participants' : `Category: ${category?.name ?? '—'}`}</td><td className="p-3">{item.delivery_channels.join(', ')}</td><td className="p-3">{new Date(item.created_at).toLocaleString()}</td><td className="p-3">{item.status}</td></tr>; })}</tbody></table></div>}</main>;
}
