import { NextResponse } from 'next/server';
import { hasPermission, loadAuthContext } from '@/lib/auth/permissions';
import { createAdminClient } from '@/lib/supabase/admin';
import { createClient } from '@/lib/supabase/server';

type JsonRecord = Record<string, unknown>;
type ReportRegistration = { id: string; category_id: string; status: string; created_at: string };
type ReportPayment = { registration_id: string; amount_due: number; amount_paid: number; amount_refunded: number; status: string; metadata: JsonRecord | null; created_at: string };
type ReportCategory = { id: string; name: string; max_slots: number | null; confirmed_count: number };

async function authorize(eventId: string) {
  const context = await loadAuthContext(); if (!context) return { response: NextResponse.json({ error: 'Authentication required' }, { status: 401 }) } as const;
  const internalAdmin = context.internalRoles.includes('admin') || context.internalRoles.includes('super_admin'); let membership = context.memberships[0]; for (const item of context.memberships) { if (await hasPermission(item.organization_id, 'view_reports', eventId)) { membership = item; break; } }
  if (!internalAdmin && (!membership || !(await hasPermission(membership.organization_id, 'view_reports', eventId)))) return { response: NextResponse.json({ error: 'Report access requires view_reports permission' }, { status: 403 }) } as const;
  const supabase = await createClient(); let eventQuery = supabase.from('events').select('id,organization_id,name,overall_capacity').eq('id', eventId); if (membership && !internalAdmin) eventQuery = eventQuery.eq('organization_id', membership.organization_id); const { data: event } = await eventQuery.maybeSingle(); if (!event) return { response: NextResponse.json({ error: 'Event not found' }, { status: 404 }) } as const;
  return { context, event, admin: createAdminClient(), financialAccess: internalAdmin || !!membership && await hasPermission(event.organization_id, 'view_financials', eventId) } as const;
}

function dateFilter<T extends { gte: (column: string, value: string) => T; lte: (column: string, value: string) => T }>(query: T, from: string | null, to: string | null) { let result = query; if (from) result = result.gte('created_at', from); if (to) result = result.lte('created_at', to); return result; }
function numberValue(value: unknown) { const result = Number(value); return Number.isFinite(result) ? result : 0; }

export async function GET(request: Request, { params }: { params: { eventId: string } }) {
  const auth = await authorize(params.eventId); if ('response' in auth) return auth.response; const url = new URL(request.url); const from = url.searchParams.get('from'); const to = url.searchParams.get('to'); const categoryId = url.searchParams.get('category_id'); const registrationStatus = url.searchParams.get('registration_status'); const paymentStatus = url.searchParams.get('payment_status'); const exportCsv = url.searchParams.get('export') === 'csv';
  const admin = auth.admin;
  let registrationsQuery = admin.from('registrations').select('id,category_id,status,created_at').eq('event_id', params.eventId); if (categoryId) registrationsQuery = registrationsQuery.eq('category_id', categoryId); if (registrationStatus) registrationsQuery = registrationsQuery.eq('status', registrationStatus as never); registrationsQuery = dateFilter(registrationsQuery, from, to);
  let paymentsQuery = admin.from('payments').select('registration_id,amount_due,amount_paid,amount_refunded,status,metadata,created_at').eq('event_id', params.eventId); if (paymentStatus) paymentsQuery = paymentsQuery.eq('status', paymentStatus as never); paymentsQuery = dateFilter(paymentsQuery, from, to);
  const [{ data: registrations, error: registrationsError }, { data: categories }, { data: payments }, { data: refunds }, { data: fees }, { data: promos }, { data: claims }, { data: results }, { data: certificates }, { data: emails }] = await Promise.all([
    registrationsQuery,
    admin.from('race_categories').select('id,name,max_slots,confirmed_count').eq('event_id', params.eventId).order('name'),
    paymentsQuery,
    dateFilter(admin.from('refunds').select('amount,status,created_at').eq('event_id', params.eventId), from, to),
    dateFilter(admin.from('platform_fees').select('amount,status,created_at').eq('event_id', params.eventId), from, to),
    dateFilter(admin.from('promo_code_redemptions').select('discount_amount,status,created_at').eq('event_id', params.eventId), from, to),
    dateFilter(admin.from('race_kit_claims').select('registration_id,claimed_at,created_at').eq('event_id', params.eventId), from, to),
    dateFilter(admin.from('results').select('result_status,validation_status,result_batch_id,created_at').eq('event_id', params.eventId), from, to),
    dateFilter(admin.from('certificates').select('status,created_at').eq('event_id', params.eventId), from, to),
    dateFilter(admin.from('email_messages').select('status,created_at').eq('event_id', params.eventId), from, to),
  ]);
  if (registrationsError) return NextResponse.json({ error: 'Reports could not be loaded' }, { status: 500 });
  const registrationRows = (registrations ?? []) as unknown as ReportRegistration[]; const categoryRows = (categories ?? []) as unknown as ReportCategory[]; const paymentRows = (payments ?? []) as unknown as ReportPayment[]; const confirmed = registrationRows.filter((row) => row.status === 'confirmed').length; const categoryReport = categoryRows.map((category) => { const rows = registrationRows.filter((row) => row.category_id === category.id); const categoryPayments = paymentRows.filter((payment) => rows.some((row) => row.id === payment.registration_id) && ['succeeded', 'partially_refunded', 'refunded'].includes(payment.status)); return { id: category.id, name: category.name, registrations: rows.length, confirmed: rows.filter((row) => row.status === 'confirmed').length, capacity: category.max_slots, available: category.max_slots === null ? null : Math.max(category.max_slots - rows.filter((row) => row.status === 'confirmed').length, 0), gross_sales: categoryPayments.reduce((sum, payment) => sum + numberValue(payment.metadata?.registration_amount ?? payment.amount_due), 0) }; });
  const successfulPayments = paymentRows.filter((payment) => ['succeeded', 'partially_refunded', 'refunded'].includes(payment.status)); const grossSales = successfulPayments.reduce((sum, payment) => sum + numberValue(payment.metadata?.registration_amount ?? payment.amount_due), 0); const paidTotal = successfulPayments.reduce((sum, payment) => sum + numberValue(payment.amount_paid), 0); const discountTotal = (promos ?? []).filter((row) => row.status === 'applied').reduce((sum, row) => sum + numberValue(row.discount_amount), 0); const refundTotal = (refunds ?? []).filter((row) => row.status === 'succeeded').reduce((sum, row) => sum + numberValue(row.amount), 0); const platformFeeTotal = (fees ?? []).filter((row) => ['accrued', 'collected'].includes(row.status)).reduce((sum, row) => sum + numberValue(row.amount), 0); const processingFeeTotal = successfulPayments.reduce((sum, payment) => sum + numberValue(payment.metadata?.processing_fee), 0); const netRevenue = Math.max(0, paidTotal - refundTotal - platformFeeTotal - processingFeeTotal);
  const resultRows = (results ?? []) as Array<{ result_status: string; validation_status: string; result_batch_id: string }>; const validResultIds = new Set(resultRows.filter((row) => row.validation_status === 'valid').map((row) => row.result_batch_id)); const resultCounts = { finished: 0, dnf: 0, dns: 0, dq: 0 }; for (const row of resultRows) if (row.validation_status === 'valid' && row.result_status in resultCounts) resultCounts[row.result_status as keyof typeof resultCounts] += 1;
  const emailCounts = { queued: 0, delivered: 0, failed: 0, bounced: 0, suppressed: 0 }; for (const row of emails ?? []) if (row.status in emailCounts) emailCounts[row.status as keyof typeof emailCounts] += 1;
  const report = { event: auth.event, filters: { from, to, category_id: categoryId, registration_status: registrationStatus, payment_status: paymentStatus }, summary: { total_registrations: registrationRows.length, confirmed_registrations: confirmed, capacity: auth.event.overall_capacity, available_slots: auth.event.overall_capacity === null ? null : Math.max(auth.event.overall_capacity - confirmed, 0) }, category_performance: categoryReport, operational: { race_kits_claimed: (claims ?? []).length, race_kits_unclaimed: Math.max(confirmed - (claims ?? []).length, 0), results: resultCounts, certificates_issued: (certificates ?? []).filter((row) => row.status === 'issued').length, published_result_batches: validResultIds.size }, financial: auth.financialAccess ? { gross_registration_sales: grossSales, discounts: discountTotal, refunds: refundTotal, racedeck_fees: platformFeeTotal + processingFeeTotal, paid_total: paidTotal, net_organizer_revenue: netRevenue, payments: { total: paymentRows.length, successful: successfulPayments.length, by_status: paymentRows.reduce<Record<string, number>>((map, row) => ({ ...map, [row.status]: (map[row.status] ?? 0) + 1 }), {}) } } : null, email_delivery: emailCounts, access: { financial: auth.financialAccess } };
  if (exportCsv) { const rows = [['Metric', 'Value'], ['Total Registrations', report.summary.total_registrations], ['Confirmed Registrations', report.summary.confirmed_registrations], ['Capacity', report.summary.capacity ?? ''], ['Available Slots', report.summary.available_slots ?? ''], ['Race Kits Claimed', report.operational.race_kits_claimed], ['Race Kits Unclaimed', report.operational.race_kits_unclaimed], ['Finished Results', report.operational.results.finished], ['DNF Results', report.operational.results.dnf], ['DNS Results', report.operational.results.dns], ['DQ Results', report.operational.results.dq], ['Certificates Issued', report.operational.certificates_issued], ...report.financial ? [['Gross Registration Sales', report.financial.gross_registration_sales], ['Discounts', report.financial.discounts], ['Refunds', report.financial.refunds], ['RaceDeck Fees', report.financial.racedeck_fees], ['Net Organizer Revenue', report.financial.net_organizer_revenue]] : []].map((row) => row.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(',')); return new NextResponse(rows.join('\r\n'), { headers: { 'Content-Type': 'text/csv; charset=utf-8', 'Content-Disposition': `attachment; filename="${params.eventId}-report.csv"` } }); }
  return NextResponse.json(report);
}
