import { createAdminClient } from '@/lib/supabase/admin';
import { AdminPage, DataTable, EmptyState, StatCard, StatusBadge, Toolbar, ActionLink } from '@/components/admin/admin-ui';

export default async function AdminSupportPage() {
  const db = createAdminClient();
  const [{ data }, { count: open }, { count: progress }, { count: resolved }] = await Promise.all([
    db.from('support_cases').select('id,case_reference,subject,case_type,priority,status,opened_at,updated_at,organization_id,event_id,registrations(registration_number),organizations!support_cases_organization_id_fkey(name)').order('updated_at', { ascending: false }).limit(100),
    db.from('support_cases').select('id', { count: 'exact', head: true }).eq('status', 'open'), db.from('support_cases').select('id', { count: 'exact', head: true }).eq('status', 'in_progress'), db.from('support_cases').select('id', { count: 'exact', head: true }).eq('status', 'resolved'),
  ]);
  const rows = data ?? [];
  return <AdminPage title="Support / Issues" description="Manage participant and organizer concerns affecting RaceDeck."><section className="grid gap-4 sm:grid-cols-4"><StatCard label="Open" value={open ?? 0} tone="orange" /><StatCard label="In progress" value={progress ?? 0} tone="amber" /><StatCard label="Resolved" value={resolved ?? 0} tone="green" /><StatCard label="Cases in view" value={rows.length} /></section><Toolbar placeholder="Search case, subject, participant, or organizer..."><select aria-label="Case status" className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option>All case statuses</option><option>Open</option><option>In progress</option><option>Resolved</option><option>Closed</option></select><select aria-label="Priority" className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option>All priorities</option><option>Urgent</option><option>High</option><option>Normal</option></select></Toolbar>{rows.length ? <DataTable headers={['Case','Requester context','Category','Priority','Status','Updated','Actions']}>{rows.map((row) => <tr key={row.id} className="hover:bg-slate-50"><td className="px-4 py-4"><p className="font-bold">{row.case_reference}</p><p className="mt-1 text-slate-700">{row.subject}</p></td><td className="px-4 py-4"><p>{row.organizations?.name ?? 'Participant'}</p><p className="text-xs text-slate-500">{row.registrations?.registration_number ?? 'No registration linked'}</p></td><td className="px-4 py-4 capitalize">{row.case_type.replaceAll('_', ' ')}</td><td className="px-4 py-4"><StatusBadge value={row.priority} tone={row.priority === 'urgent' || row.priority === 'high' ? 'red' : undefined} /></td><td className="px-4 py-4"><StatusBadge value={row.status} /></td><td className="px-4 py-4 text-xs text-slate-500">{new Date(row.updated_at).toLocaleString('en-PH')}</td><td className="px-4 py-4"><ActionLink href={`/admin/support/${row.id}`}>Open</ActionLink></td></tr>)}</DataTable> : <EmptyState message="No open support cases." />}</AdminPage>;
}
