import { NextResponse } from 'next/server';
import { z } from 'zod';
import { hasPermission, loadAuthContext } from '@/lib/auth/permissions';
import { createAdminClient } from '@/lib/supabase/admin';
import { createClient } from '@/lib/supabase/server';
import { CUSTOM_FIELD_TYPES, isSystemRegistrationFieldLabel } from '@/lib/registration-form/config';
const fieldSchema = z.object({label:z.string().trim().min(1).max(160),field_type:z.enum(CUSTOM_FIELD_TYPES),is_required:z.boolean(),is_active:z.boolean(),display_order:z.number().int().nonnegative()});
async function access(eventId:string, write=false){const context=await loadAuthContext();if(!context)return{response:NextResponse.json({error:'Authentication required'},{status:401})}as const;const membership=context.memberships[0];if(!membership)return{response:NextResponse.json({error:'Organization access required'},{status:403})}as const;if(!(await hasPermission(membership.organization_id,write?'edit_events':'view_events',eventId)))return{response:NextResponse.json({error:'You do not have access to this event'},{status:403})}as const;const supabase=await createClient();const{data:event}=await supabase.from('events').select('id').eq('id',eventId).eq('organization_id',membership.organization_id).maybeSingle();if(!event)return{response:NextResponse.json({error:'Event not found'},{status:404})}as const;return{context,membership,supabase}as const}
export async function GET(_r:Request,{params}:{params:{eventId:string}}){const result=await access(params.eventId);if('response'in result)return result.response;const{data:fields,error}=await result.supabase.from('event_registration_fields').select('id,event_id,label,field_type,is_required,is_active,display_order,created_at').eq('event_id',params.eventId).order('display_order').order('created_at');if(error){console.error('Unable to load registration form fields',error);return NextResponse.json({error:'Registration form could not be loaded'},{status:500})}const ids=(fields??[]).map(f=>f.id);const{data:options}=ids.length?await result.supabase.from('event_registration_field_options').select('id,field_id,label,value,display_order').in('field_id',ids).order('display_order'): {data:[]};return NextResponse.json((fields??[]).map(f=>({...f,options:(options??[]).filter(o=>o.field_id===f.id)})))}
export async function POST(request:Request,{params}:{params:{eventId:string}}){const result=await access(params.eventId,true);if('response'in result)return result.response;const parsed=fieldSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Invalid registration field details'},{status:400});if(isSystemRegistrationFieldLabel(parsed.data.label))return NextResponse.json({error:'RaceDeck default participant fields are managed by the system and cannot be added as custom fields'},{status:409});const admin=createAdminClient();const{data,error}=await admin.from('event_registration_fields').insert({...parsed.data,event_id:params.eventId}).select('*').single();if(error){console.error('Unable to create registration form field',error);return NextResponse.json({error:'Registration field could not be created'},{status:500})}return NextResponse.json(data,{status:201})}
