/* eslint-disable @typescript-eslint/no-explicit-any */
'use client';
import { useEffect, useState } from 'react';

export default function RegisterPage({ params }: { params: { eventId: string } }) {
  const [data, setData] = useState<any>(null); const [category, setCategory] = useState(''); const [promoCode, setPromoCode] = useState(''); const [answers, setAnswers] = useState<Record<string, string>>({}); const [acceptWaiver, setAcceptWaiver] = useState(false); const [message, setMessage] = useState('Loading registration…'); const [busy, setBusy] = useState(false);
  useEffect(() => { void fetch(`/api/events/${params.eventId}/registration-info`).then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body); setCategory(body.categories[0]?.id ?? ''); setMessage(''); }).catch(error => setMessage(error.message)); }, [params.eventId]);
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); const response = await fetch(`/api/events/${params.eventId}/register`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ category_id: category, answers, promo_code: promoCode || undefined, accept_waiver: acceptWaiver, idempotency_key: crypto.randomUUID() }) }); const body = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) { setMessage(body.error ?? 'Registration could not be started.'); return; } if (body.checkout_url) window.location.assign(body.checkout_url); }
  if (!data) return <main className="mx-auto max-w-2xl p-6"><p>{message}</p></main>;
  return <main className="mx-auto max-w-2xl space-y-6 p-6"><header><h1 className="text-2xl font-semibold">Register for {data.event.name}</h1><p className="text-sm text-gray-600">{data.event.event_date} · {data.event.venue ?? data.event.address ?? 'Venue to be announced'}</p></header>{message && <p role="alert">{message}</p>}<form onSubmit={submit} className="space-y-4 rounded border p-4"><label className="block text-sm">Race Category<select required value={category} onChange={e => setCategory(e.target.value)} className="mt-1 w-full rounded border p-2">{data.categories.map((item: any) => <option key={item.id} value={item.id}>{item.name} · PHP {item.registration_fee}</option>)}</select></label><label className="block text-sm">Promo code (optional)<input value={promoCode} onChange={e => setPromoCode(e.target.value.toUpperCase())} className="mt-1 w-full rounded border p-2" autoComplete="off" /></label>{data.fields.map((field: any) => <label key={field.id} className="block text-sm">{field.label}{field.is_required ? ' *' : ''}{field.field_type === 'long_text' ? <textarea required={field.is_required} value={answers[field.id] ?? ''} onChange={e => setAnswers({ ...answers, [field.id]: e.target.value })} className="mt-1 w-full rounded border p-2" /> : field.field_type === 'dropdown' || field.field_type === 'radio' ? <select required={field.is_required} value={answers[field.id] ?? ''} onChange={e => setAnswers({ ...answers, [field.id]: e.target.value })} className="mt-1 w-full rounded border p-2"><option value="">Select</option>{(field.event_registration_field_options ?? []).map((option: any) => <option key={option.id} value={option.value}>{option.label}</option>)}</select> : <input required={field.is_required} value={answers[field.id] ?? ''} onChange={e => setAnswers({ ...answers, [field.id]: e.target.value })} className="mt-1 w-full rounded border p-2" />}</label>)}{data.waiver && <label className="flex items-start gap-2 text-sm"><input type="checkbox" required checked={acceptWaiver} onChange={e => setAcceptWaiver(e.target.checked)} /><span>I have read and accept <span className="font-medium">{data.waiver.title}</span> (version {data.waiver.version}).{data.waiver.content && <span className="mt-1 block max-h-40 overflow-auto whitespace-pre-wrap rounded bg-gray-50 p-2 text-xs">{data.waiver.content}</span>}</span></label>}<button disabled={busy || !category} className="rounded bg-black px-4 py-2 text-sm text-white">{busy ? 'Starting checkout…' : 'Continue to Payment'}</button></form></main>;
}
