import { NextResponse } from 'next/server';
import { z } from 'zod';
import { hasPermission, loadAuthContext } from '@/lib/auth/permissions';
import { createAdminClient } from '@/lib/supabase/admin';
import { createClient } from '@/lib/supabase/server';
import { CUSTOM_FIELD_TYPES, isSystemRegistrationFieldLabel } from '@/lib/registration-form/config';
const schema=z.object({label:z.string().trim().min(1).max(160),field_type:z.enum(CUSTOM_FIELD_TYPES),is_required:z.boolean(),is_active:z.boolean(),display_order:z.number().int().nonnegative()});
async function authorized(eventId:string,fieldId:string){const context=await loadAuthContext();if(!context)return{response:NextResponse.json({error:'Authentication required'},{status:401})}as const;const membership=context.memberships[0];if(!membership)return{response:NextResponse.json({error:'Organization access required'},{status:403})}as const;if(!(await hasPermission(membership.organization_id,'edit_events',eventId)))return{response:NextResponse.json({error:'Event edit permission required'},{status:403})}as const;const supabase=await createClient();const{data:event}=await supabase.from('events').select('id').eq('id',eventId).eq('organization_id',membership.organization_id).maybeSingle();if(!event)return{response:NextResponse.json({error:'Event not found'},{status:404})}as const;const{data:field}=await supabase.from('event_registration_fields').select('id,field_type').eq('id',fieldId).eq('event_id',eventId).maybeSingle();if(!field)return{response:NextResponse.json({error:'Field not found for this event'},{status:404})}as const;return{context,membership,supabase,field}as const}
export async function PATCH(request:Request,{params}:{params:{eventId:string;fieldId:string}}){const result=await authorized(params.eventId,params.fieldId);if('response'in result)return result.response;const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Invalid registration field details'},{status:400});if(isSystemRegistrationFieldLabel(parsed.data.label))return NextResponse.json({error:'RaceDeck default participant fields are managed by the system and cannot be used as custom fields'},{status:409});const admin=createAdminClient();const{count}=await admin.from('registration_responses').select('id',{count:'exact',head:true}).eq('field_id',params.fieldId);if(count&&parsed.data.field_type!==result.field.field_type)return NextResponse.json({error:'Field type cannot change after responses exist'},{status:409});const{data,error}=await admin.from('event_registration_fields').update(parsed.data).eq('id',params.fieldId).eq('event_id',params.eventId).select('*').single();if(error){console.error('Unable to update registration field',error);return NextResponse.json({error:'Registration field could not be updated'},{status:500})}return NextResponse.json(data)}
export async function DELETE(_request:Request,{params}:{params:{eventId:string;fieldId:string}}){const result=await authorized(params.eventId,params.fieldId);if('response'in result)return result.response;const admin=createAdminClient();const{count}=await admin.from('registration_responses').select('id',{count:'exact',head:true}).eq('field_id',params.fieldId);if((count??0)>0)return NextResponse.json({error:'This field has participant responses and cannot be deleted'},{status:409});const{error}=await admin.from('event_registration_fields').delete().eq('id',params.fieldId).eq('event_id',params.eventId);if(error){console.error('Unable to delete registration field',error);return NextResponse.json({error:'Registration field could not be deleted'},{status:500})}return NextResponse.json({ok:true})}
