import { NextResponse } from 'next/server';
import { z } from 'zod';
import { hasPermission, loadAuthContext } from '@/lib/auth/permissions';
import { createAdminClient } from '@/lib/supabase/admin';
import { createClient } from '@/lib/supabase/server';
const schema = z.object({ item_code: z.string().trim().min(1).max(80), item_name: z.string().trim().min(1).max(160), quantity: z.number().int().positive(), details: z.record(z.string(), z.any()).optional(), is_required: z.boolean(), is_active: z.boolean(), display_order: z.number().int().nonnegative() });
async function auth(eventId: string, configId: string, itemId: string) { const context = await loadAuthContext(); if (!context) return { response: NextResponse.json({ error: 'Authentication required' }, { status: 401 }) } as const; const membership = context.memberships[0]; if (!membership || !(await hasPermission(membership.organization_id, 'edit_events', eventId))) return { response: NextResponse.json({ error: 'Race kit permission required' }, { status: 403 }) } as const; const supabase = await createClient(); const { data: event } = await supabase.from('events').select('id,organization_id').eq('id', eventId).eq('organization_id', membership.organization_id).maybeSingle(); if (!event) return { response: NextResponse.json({ error: 'Event not found' }, { status: 404 }) } as const; const admin = createAdminClient(); const { data: item } = await admin.from('race_kit_items').select('*').eq('id', itemId).eq('config_id', configId).maybeSingle(); if (!item) return { response: NextResponse.json({ error: 'Item not found for this configuration' }, { status: 404 }) } as const; const { data: config } = await admin.from('race_kit_configs').select('id').eq('id', configId).eq('event_id', eventId).maybeSingle(); if (!config) return { response: NextResponse.json({ error: 'Configuration not found for this event' }, { status: 404 }) } as const; return { admin, item } as const; }
export async function PATCH(request: Request, { params }: { params: { eventId: string; configId: string; itemId: string } }) { const result = await auth(params.eventId, params.configId, params.itemId); if ('response' in result) return result.response; const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: 'Invalid race kit item' }, { status: 400 }); const { data, error } = await result.admin.from('race_kit_items').update(parsed.data).eq('id', result.item.id).select('*').single(); if (error) { console.error('Unable to update race kit item', error); return NextResponse.json({ error: 'Race kit item could not be updated' }, { status: 500 }); } return NextResponse.json(data); }
export async function DELETE(_request: Request, { params }: { params: { eventId: string; configId: string; itemId: string } }) { const result = await auth(params.eventId, params.configId, params.itemId); if ('response' in result) return result.response; const { count } = await result.admin.from('race_kit_claims').select('id', { count: 'exact', head: true }).eq('config_id', params.configId); if ((count ?? 0) > 0) return NextResponse.json({ error: 'This item cannot be deleted because claim history exists; deactivate it instead' }, { status: 409 }); const { error } = await result.admin.from('race_kit_items').delete().eq('id', result.item.id); if (error) { console.error('Unable to delete race kit item', error); return NextResponse.json({ error: 'Race kit item could not be deleted' }, { status: 500 }); } return NextResponse.json({ ok: true }); }
