"use client";
import { FormEvent, useEffect, useState } from 'react';
type Verification = { status:string; legal_name:string|null; business_name:string|null; registration_number:string|null; reviewer_notes:string|null; document_storage_references: unknown[] };
export default function VerificationPage() {
  const [form, setForm] = useState({legal_name:'',business_name:'',registration_number:''}); const [verification,setVerification]=useState<Verification|null>(null); const [message,setMessage]=useState('Loading verification…'); const [busy,setBusy]=useState(false);
  async function load(){ const r=await fetch('/api/organizer/verification'); if(!r.ok){setMessage('Verification could not be loaded.');return;} const d=await r.json(); setVerification(d); if(d)setForm({legal_name:d.legal_name??'',business_name:d.business_name??'',registration_number:d.registration_number??''}); setMessage(''); }
  useEffect(()=>{void load();},[]);
  async function save(e:FormEvent){e.preventDefault();setBusy(true);const r=await fetch('/api/organizer/verification',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,legal_name:form.legal_name||null,business_name:form.business_name||null,registration_number:form.registration_number||null})});setBusy(false);setMessage(r.ok?'Draft saved.':(await r.json()).error??'Save failed.');await load();}
  async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const input=e.currentTarget.elements.namedItem('file');if(!(input instanceof HTMLInputElement)||!input.files?.[0])return;setBusy(true);const body=new FormData();body.append('file',input.files[0]);const r=await fetch('/api/organizer/verification/documents',{method:'POST',body});setBusy(false);setMessage(r.ok?'Document uploaded.':(await r.json()).error??'Upload failed.');e.currentTarget.reset();await load();}
  async function submit(){setBusy(true);const r=await fetch('/api/organizer/verification/submit',{method:'POST'});setBusy(false);setMessage(r.ok?'Submitted for RaceDeck review.':(await r.json()).error??'Submission failed.');await load();}
  const locked=verification?.status==='pending_review'||verification?.status==='approved';
  return <main className="mx-auto max-w-3xl space-y-6 p-6"><div><h1 className="text-2xl font-semibold">Organizer verification</h1><p className="text-sm text-gray-600">Status: <span className="font-medium">{verification?.status??'draft'}</span></p></div>{message&&<p role="status" className="text-sm">{message}</p>}{verification?.reviewer_notes&&<div className="rounded border p-3 text-sm"><strong>Reviewer feedback:</strong> {verification.reviewer_notes}</div>}<form onSubmit={save} className="space-y-4">{(['legal_name','business_name','registration_number'] as const).map(k=><label key={k} className="block space-y-1 text-sm"><span className="capitalize">{k.replaceAll('_',' ')}</span><input disabled={locked} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="w-full rounded border p-2" /></label>)}<button disabled={busy||locked} className="rounded bg-black px-4 py-2 text-white disabled:opacity-50">Save draft</button></form><form onSubmit={upload} className="space-y-2"><label className="block text-sm">Verification document<input disabled={locked||busy} name="file" required type="file" accept="application/pdf,image/jpeg,image/png" className="mt-1 block w-full rounded border p-2" /></label><button disabled={busy||locked} className="rounded border px-4 py-2 disabled:opacity-50">Upload document</button></form>{!locked&&<button disabled={busy} onClick={submit} className="rounded bg-black px-4 py-2 text-white disabled:opacity-50">Submit for review</button>}</main>;
}
