import crypto from 'node:crypto';
import { NextResponse } from 'next/server';
import { z } from 'zod';
import { createAdminClient } from '@/lib/supabase/admin';
import { createClient } from '@/lib/supabase/server';
import { PayMongoProvider } from '@/lib/payments/paymongo.provider';
import { reserveRegistrationSlot } from '@/lib/registrations/slot.service';
import { calculatePaymentTotal } from '@/lib/payments/pricing.service';
const schema = z.object({ category_id: z.string().uuid(), answers: z.record(z.string(), z.string().max(4000)).default({}), promo_code: z.string().trim().min(3).max(64).optional(), accept_waiver: z.boolean().default(false), idempotency_key: z.string().trim().min(16).max(120) });
const registrationNumber = () => `REG-${new Date().getUTCFullYear()}-${crypto.randomInt(100000, 999999)}`;
type ServerRpcClient = { rpc(name: string, args: Record<string, unknown>): Promise<{ data: unknown; error: { message: string } | null }> };
export async function POST(request: Request, { params }: { params: { eventId: string } }) {
  const supabase = await createClient(); const { data: auth } = await supabase.auth.getUser(); if (!auth.user) return NextResponse.json({ error: 'Authentication required' }, { status: 401 });
  const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: 'Invalid registration details' }, { status: 400 }); const admin = createAdminClient();
  const { data: existing } = await admin.from('payments').select('id,registration_id,checkout_url,status,registrations!inner(user_id,event_id)').eq('gateway', 'paymongo').eq('idempotency_key', parsed.data.idempotency_key).maybeSingle(); if (existing) { const owner = Array.isArray(existing.registrations) ? existing.registrations[0] : existing.registrations; if (owner?.user_id !== auth.user.id || owner.event_id !== params.eventId) return NextResponse.json({ error: 'Registration request is not available' }, { status: 409 }); return NextResponse.json({ payment_id: existing.id, registration_id: existing.registration_id, checkout_url: existing.checkout_url, status: existing.status }); }
  const { data: event } = await admin.from('events').select('id,organization_id,name,event_date,registration_opens_at,registration_closes_at,registration_availability,lifecycle_status,review_status').eq('id', params.eventId).maybeSingle(); if (!event || event.lifecycle_status !== 'published' || event.review_status !== 'approved' || event.registration_availability !== 'open') return NextResponse.json({ error: 'Registration is not currently available' }, { status: 409 });
  const now = Date.now(); if ((event.registration_opens_at && now < Date.parse(event.registration_opens_at)) || (event.registration_closes_at && now >= Date.parse(event.registration_closes_at))) return NextResponse.json({ error: 'Registration is not currently available' }, { status: 409 });
  const { data: waiver } = await admin.from('event_waivers').select('id').eq('event_id', event.id).eq('organization_id', event.organization_id).eq('status', 'published').maybeSingle(); if (waiver && !parsed.data.accept_waiver) return NextResponse.json({ error: 'You must accept the current event waiver before registering' }, { status: 400 });
  const { data: category } = await admin.from('race_categories').select('id,name,registration_fee,registration_availability').eq('id', parsed.data.category_id).eq('event_id', event.id).maybeSingle(); if (!category || category.registration_availability !== 'open') return NextResponse.json({ error: 'Selected category is unavailable' }, { status: 409 });
  const promoCode = parsed.data.promo_code ? parsed.data.promo_code.toUpperCase() : null; const { data: promo } = promoCode ? await admin.from('promo_codes').select('id,code,event_id,currency,status').eq('event_id', event.id).eq('code', promoCode).maybeSingle() : { data: null }; if (promoCode && !promo) return NextResponse.json({ error: 'Promo code is invalid for this event' }, { status: 400 });
  const { data: profile } = await admin.from('user_profiles').select('first_name,last_name,birthdate,mobile,address,emergency_contact_name,emergency_contact_number,default_shirt_size').eq('id', auth.user.id).maybeSingle(); if (!profile?.first_name || !profile.last_name || !auth.user.email) return NextResponse.json({ error: 'Complete your participant profile before registering' }, { status: 400 });
  const { data: fields } = await admin.from('event_registration_fields').select('id,label,is_required,is_active').eq('event_id', event.id).eq('is_active', true); for (const field of fields ?? []) if (field.is_required && !parsed.data.answers[field.id]?.trim()) return NextResponse.json({ error: `${field.label} is required` }, { status: 400 });
  const holdExpires = new Date(Date.now() + 15 * 60 * 1000).toISOString(); const { data: hold, error: holdError } = await reserveRegistrationSlot(admin, event.id, category.id, auth.user.id, holdExpires); if (holdError || !hold) return NextResponse.json({ error: 'Selected category is full or could not be reserved' }, { status: 409 });
  const { data: created, error: registrationError } = await admin.from('registrations').insert({ registration_number: registrationNumber(), event_id: event.id, category_id: category.id, user_id: auth.user.id, hold_id: hold, first_name: profile.first_name, last_name: profile.last_name, birthdate: profile.birthdate, email: auth.user.email, mobile: profile.mobile, address: profile.address, emergency_contact_name: profile.emergency_contact_name, emergency_contact_number: profile.emergency_contact_number, shirt_size: profile.default_shirt_size, status: 'pending_payment' }).select('id,registration_number').single(); if (registrationError || !created) { await admin.from('registration_holds').update({ status: 'released' }).eq('id', hold); return NextResponse.json({ error: 'Registration could not be created' }, { status: 409 }); } if (waiver) { const { error: waiverError } = await admin.from('event_waiver_acceptances').insert({ event_waiver_id: waiver.id, organization_id: event.organization_id, event_id: event.id, registration_id: created.id, participant_id: auth.user.id, source_context: 'participant_registration' }); if (waiverError) { await admin.from('registrations').update({ status: 'cancelled' }).eq('id', created.id); await admin.from('registration_holds').update({ status: 'released' }).eq('id', hold); return NextResponse.json({ error: 'Waiver acceptance could not be recorded' }, { status: 500 }); } } await admin.from('registration_activity').insert({ registration_id: created.id, action: 'created', actor: auth.user.id });
  const answerRows = Object.entries(parsed.data.answers).filter(([fieldId]) => (fields ?? []).some(field => field.id === fieldId)).map(([field_id, value]) => ({ registration_id: created.id, field_id, value })); if (answerRows.length) await admin.from('registration_responses').insert(answerRows);
  const amount = Number(category.registration_fee); const { data: payment, error: paymentError } = await admin.from('payments').insert({ registration_id: created.id, event_id: event.id, organization_id: event.organization_id, gateway: 'paymongo', idempotency_key: parsed.data.idempotency_key, amount_due: amount, currency: 'PHP', status: 'pending', expires_at: holdExpires, metadata: { registration_amount: amount, processing_fee: 0, platform_fee: 0, discount_amount: 0, total_amount: amount } }).select('id').single(); if (paymentError || !payment) { await admin.from('registrations').update({ status: 'cancelled' }).eq('id', created.id); await admin.from('registration_holds').update({ status: 'released' }).eq('id', hold); return NextResponse.json({ error: 'Payment could not be initialized' }, { status: 500 }); }
  let discount = 0; if (promo) { const { error: redemptionError } = await (admin as unknown as ServerRpcClient).rpc('redeem_promo_code', { p_promo_code_id: promo.id, p_user_id: auth.user.id, p_registration_id: created.id, p_event_id: event.id, p_category_id: category.id, p_payment_id: payment.id, p_eligible_amount: amount, p_currency: 'PHP' }); if (redemptionError) { await admin.from('payments').update({ status: 'cancelled', failure_message: 'Promo code could not be applied' }).eq('id', payment.id); await admin.from('registrations').update({ status: 'cancelled' }).eq('id', created.id); await admin.from('registration_holds').update({ status: 'released' }).eq('id', hold); return NextResponse.json({ error: redemptionError.message }, { status: 409 }); } const { data: redemption } = await admin.from('promo_code_redemptions').select('discount_amount').eq('payment_id', payment.id).eq('registration_id', created.id).maybeSingle(); discount = Number(redemption?.discount_amount ?? 0); }
  const pricing = calculatePaymentTotal({ registrationAmount: amount, discountAmount: discount }); const total = pricing.totalAmount; const { error: pricingError } = await admin.from('payments').update({ amount_due: total, metadata: { registration_amount: amount, processing_fee: pricing.processingFee, platform_fee: pricing.platformFee, discount_amount: pricing.discountAmount, total_amount: total } }).eq('id', payment.id); if (pricingError) { await admin.from('payments').update({ status: 'cancelled', failure_message: 'Payment pricing could not be saved' }).eq('id', payment.id); await admin.from('registrations').update({ status: 'cancelled' }).eq('id', created.id); await admin.from('registration_holds').update({ status: 'released' }).eq('id', hold); return NextResponse.json({ error: 'Payment could not be initialized' }, { status: 500 }); } await admin.from('registration_activity').insert({ registration_id: created.id, action: 'payment_initiated', actor: auth.user.id });
  try { const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? new URL(request.url).origin; const checkout = await new PayMongoProvider().createCheckout({ amount: total, currency: 'PHP', description: `${event.name} — ${category.name}`, reference: created.registration_number, successUrl: `${siteUrl}/my-races/${created.id}`, cancelUrl: `${siteUrl}/my-races/${created.id}` }); await admin.from('payments').update({ gateway_payment_id: checkout.gatewayPaymentId, checkout_url: checkout.checkoutUrl }).eq('id', payment.id); await admin.from('registration_holds').update({ status: 'converted' }).eq('id', hold); return NextResponse.json({ payment_id: payment.id, registration_id: created.id, checkout_url: checkout.checkoutUrl, status: 'pending' }, { status: 201 }); } catch (error) { console.error('Unable to create payment checkout', error); await admin.from('payments').update({ status: 'cancelled', failure_message: 'Payment checkout could not be created' }).eq('id', payment.id); await (admin as unknown as ServerRpcClient).rpc('reverse_promo_redemption', { p_payment_id: payment.id, p_registration_id: created.id }); await admin.from('registrations').update({ status: 'cancelled' }).eq('id', created.id); await admin.from('registration_holds').update({ status: 'released' }).eq('id', hold); return NextResponse.json({ error: 'Payment checkout could not be created' }, { status: 502 }); }
}
