"use client";
import { FormEvent, useEffect, useState } from 'react';
const fields = ['name','logo_url','description','contact_person','contact_email','contact_phone','address','website','social_links'] as const;
type Form = Record<(typeof fields)[number], string>;
const empty: Form = { name:'', logo_url:'', description:'', contact_person:'', contact_email:'', contact_phone:'', address:'', website:'', social_links:'' };
export default function OrganizationPage() {
  const [form, setForm] = useState<Form>(empty); const [state, setState] = useState('Loading organization…'); const [busy, setBusy] = useState(false);
  useEffect(() => { fetch('/api/organizer/organization').then(async (r) => { if (!r.ok) throw new Error(); const data = await r.json(); setForm(Object.fromEntries(fields.map((key) => [key, key === 'social_links' ? JSON.stringify(data[key] ?? {}, null, 2) : data[key] ?? ''])) as Form); setState(''); }).catch(() => setState('Organization could not be loaded.')); }, []);
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); setState(''); let socialLinks: Record<string, string> | null = null; try { socialLinks = form.social_links.trim() ? JSON.parse(form.social_links) : null; } catch { setBusy(false); setState('Social links must be valid JSON.'); return; } const payload = { ...form, social_links: socialLinks, ...Object.fromEntries(fields.filter((key) => key !== 'name' && key !== 'social_links').map((key) => [key, form[key] || null])) }; const response = await fetch('/api/organizer/organization', { method:'PUT', headers:{'Content-Type':'application/json'}, body:JSON.stringify(payload) }); setBusy(false); setState(response.ok ? 'Organization profile saved.' : (await response.json()).error ?? 'Save failed.'); }
  return <main className="mx-auto max-w-3xl space-y-6 p-6"><div><h1 className="text-2xl font-semibold">Organization profile</h1><p className="text-sm text-gray-600">Complete the public organizer information used on RaceDeck.</p></div>{state && <p role="status" className="text-sm">{state}</p>}<form onSubmit={save} className="grid gap-4 sm:grid-cols-2">{fields.map((key) => <label key={key} className="space-y-1 text-sm"><span className="block capitalize">{key === 'social_links' ? 'Social links (JSON)' : key.replaceAll('_',' ')}</span>{key === 'description' || key === 'address' || key === 'social_links' ? <textarea value={form[key]} onChange={(e) => setForm({...form,[key]:e.target.value})} className="min-h-24 w-full rounded border p-2" /> : <input required={key === 'name'} type={key === 'contact_email' ? 'email' : 'text'} value={form[key]} onChange={(e) => setForm({...form,[key]:e.target.value})} className="w-full rounded border p-2" />}</label>)}<button disabled={busy} className="rounded bg-black px-4 py-2 text-white disabled:opacity-50">{busy ? 'Saving…' : 'Save profile'}</button></form></main>;
}
