'use client';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';

type Category = { name: string; distance: string; capacity: string; fee: string };
type Sponsor = { name: string; logo: string; website: string };
type UploadValue = { url: string; file: File | null };
const steps = ['Event Profile', 'Dates & Schedule', 'Location', 'Categories & Pricing', 'Race Kit Configuration', 'Content & Media', 'Sponsors & Review'];
const input = 'mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm outline-none focus:border-orange-500 focus:ring-2 focus:ring-orange-100';
const emptyCategory = (): Category => ({ name: '', distance: '', capacity: '', fee: '' });
const emptyUpload = (): UploadValue => ({ url: '', file: null });

function TextField({ label, value, onChange, type = 'text', required = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) {
  return <label className="block text-sm font-semibold text-slate-700">{label}{required && <span className="ml-1 text-orange-600">*</span>}<input required={required} type={type} value={value} onChange={(event) => onChange(event.target.value)} className={input} /></label>;
}
function Upload({ label, value, onChange, wide = false, multiple = false }: { label: string; value: UploadValue | UploadValue[]; onChange: (file: File, url: string) => void; wide?: boolean; multiple?: boolean }) {
  const preview = Array.isArray(value) ? value : [value];
  return <div><label className="block text-sm font-semibold text-slate-700">{label}<input type="file" multiple={multiple} accept="image/jpeg,image/png,image/webp" onChange={(event) => { Array.from(event.target.files ?? []).forEach((file) => onChange(file, URL.createObjectURL(file))); event.currentTarget.value = ''; }} className={input} /></label><div className="mt-2 flex flex-wrap gap-2">{preview.filter((item) => item.url).map((item, index) => <img key={`${item.url}-${index}`} src={item.url} alt={`${label} preview ${index + 1}`} className={`rounded-lg border object-cover ${wide ? 'aspect-[3/1] w-full' : 'h-24 w-24'}`} />)}</div></div>;
}

export default function CreateEventPage() {
  const router = useRouter();
  const [step, setStep] = useState(0); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ name: '', tagline: '', description: '', eventDate: '', registrationOpen: '', registrationClose: '', assembly: '', gunStart: '', cutoff: '', venue: '', city: '', province: '', address: '', mechanics: '', logo: emptyUpload(), banner: emptyUpload(), routeMap: emptyUpload() });
  const [categories, setCategories] = useState<Category[]>([]); const [posters, setPosters] = useState<UploadValue[]>([]); const [kits, setKits] = useState<string[]>([]); const [faqs, setFaqs] = useState([{ question: '', answer: '' }]);
  const [sponsors, setSponsors] = useState<Record<string, Sponsor[]>>({ 'Presented By': [], 'Official Partners': [], 'Supported By': [] });
  const update = <K extends keyof typeof form>(key: K, value: typeof form[K]) => setForm((current) => ({ ...current, [key]: value }));
  const capacity = useMemo(() => categories.reduce((sum, item) => sum + Number(item.capacity || 0), 0), [categories]);
  const missing = [!form.name.trim() && 'event name', !form.eventDate && 'event date'].filter(Boolean) as string[]; const ready = missing.length === 0;

  async function uploadAsset(eventId: string, kind: 'logo' | 'banner' | 'poster' | 'route_map', file: File) {
    const data = new FormData(); data.append('file', file); data.append('kind', kind); const response = await fetch(`/api/organizer/events/${eventId}/assets`, { method: 'POST', body: data }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error ?? `${kind} upload failed`); return body.url as string;
  }
  async function createEvent() {
    if (!ready) { setMessage(`Complete the required ${missing.join(' and ')} first.`); setStep(missing.includes('event date') ? 1 : 0); return; }
    setBusy(true); setMessage('Creating event...');
    try {
      const description = [form.tagline.trim(), form.description.trim(), form.mechanics.trim() ? `Race Mechanics\n${form.mechanics.trim()}` : ''].filter(Boolean).join('\n\n');
      const address = [form.address.trim(), form.city.trim(), form.province.trim()].filter(Boolean).join(', ');
      const response = await fetch('/api/organizer/events', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: form.name, slug: form.name.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''), description, event_date: form.eventDate, venue: form.venue, address, registration_opens_at: form.registrationOpen ? `${form.registrationOpen}T00:00:00.000Z` : null, registration_closes_at: form.registrationClose ? `${form.registrationClose}T23:59:59.000Z` : null, assembly_time: form.assembly || null, gun_start_time: form.gunStart || null, cutoff_time: form.cutoff || null, overall_capacity: capacity || null }) });
      const body = await response.json().catch(() => ({})); if (!response.ok || !body.event?.id) throw new Error(body.error ?? 'Event could not be created.'); const eventId = body.event.id as string;
      for (const category of categories.filter((item) => item.name.trim())) { const saved = await fetch(`/api/organizer/events/${eventId}/categories`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: category.name.trim(), distance_km: Number(category.distance) || null, registration_fee: Number(category.fee) || 0, max_slots: Number(category.capacity) || null, gun_start_time: form.gunStart || null, cutoff_time: form.cutoff || null, registration_availability: 'not_yet_open' }) }); if (!saved.ok) throw new Error((await saved.json().catch(() => ({}))).error ?? 'A category could not be saved.'); }
      if (form.logo.file) await uploadAsset(eventId, 'logo', form.logo.file); if (form.banner.file) await uploadAsset(eventId, 'banner', form.banner.file); if (form.routeMap.file) await uploadAsset(eventId, 'route_map', form.routeMap.file); for (const poster of posters) if (poster.file) await uploadAsset(eventId, 'poster', poster.file);
      setMessage('Event created successfully.'); router.push(`/organizer/events/${eventId}/preview`);
    } catch (error) { setMessage(error instanceof Error ? error.message : 'Event could not be created.'); } finally { setBusy(false); }
  }
  const addSponsor = (tier: string) => setSponsors((current) => ({ ...current, [tier]: [...current[tier], { name: '', logo: '', website: '' }] }));
  const editSponsor = (tier: string, index: number, patch: Partial<Sponsor>) => setSponsors((current) => ({ ...current, [tier]: current[tier].map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) }));

  return <main className="mx-auto max-w-7xl space-y-6 p-5 sm:p-7"><div className="text-sm text-slate-500"><Link href="/organizer/events">Organizer</Link> / Events / Create Event</div><header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-black text-[#071b41]">Create Event</h1><p className="mt-1 text-sm text-slate-500">Set up your race event, registration categories, event content, and public event page.</p></div><div className="flex gap-2"><button onClick={() => router.push('/organizer/events')} className="rounded-lg border px-4 py-2 text-sm font-bold">Cancel</button><button onClick={() => void createEvent()} disabled={busy} className="rounded-lg bg-orange-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{busy ? 'Creating…' : 'Create Event'}</button></div></header>{message && <p role="status" className="rounded-lg bg-orange-50 p-3 text-sm text-orange-800">{message}</p>}<div className="grid gap-6 lg:grid-cols-[235px_minmax(0,1fr)]"><aside className="h-fit rounded-2xl border border-slate-200 bg-white p-3 shadow-sm lg:sticky lg:top-24"><p className="px-3 pb-3 text-xs font-bold uppercase tracking-widest text-slate-400">Event setup</p>{steps.map((item, index) => <button key={item} onClick={() => setStep(index)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-sm font-bold ${step === index ? 'bg-[#071b41] text-white' : 'text-slate-600 hover:bg-slate-50'}`}><span className={`grid h-7 w-7 place-items-center rounded-full text-xs ${index < step ? 'bg-emerald-500 text-white' : step === index ? 'bg-orange-500 text-white' : 'bg-slate-100 text-slate-500'}`}>{index < step ? '✓' : index + 1}</span>{item}</button>)}</aside><section className="min-w-0 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><p className="text-xs font-bold uppercase tracking-widest text-orange-600">Step {step + 1} of 7</p><h2 className="mt-1 text-2xl font-black text-[#071b41]">{steps[step]}</h2>
    {step === 0 && <div className="mt-6 space-y-5"><div className="grid gap-4 sm:grid-cols-2"><TextField label="Event name" value={form.name} onChange={(v) => update('name', v)} required /><TextField label="Tagline" value={form.tagline} onChange={(v) => update('tagline', v)} /></div><div className="grid gap-4 sm:grid-cols-2"><Upload label="Event logo / thumbnail" value={form.logo} onChange={(file, url) => update('logo', { file, url })} /><Upload label="Banner image" value={form.banner} onChange={(file, url) => update('banner', { file, url })} wide /></div><TextField label="Short description" value={form.description} onChange={(v) => update('description', v)} /><label className="block text-sm font-semibold">Long description<textarea value={form.description} onChange={(e) => update('description', e.target.value)} className={`${input} min-h-40`} /></label></div>}
    {step === 1 && <div className="mt-6 grid gap-4 sm:grid-cols-2"><TextField label="Event date" type="date" value={form.eventDate} onChange={(v) => update('eventDate', v)} required /><TextField label="Registration open" type="date" value={form.registrationOpen} onChange={(v) => update('registrationOpen', v)} /><TextField label="Registration close" type="date" value={form.registrationClose} onChange={(v) => update('registrationClose', v)} /><TextField label="Assembly time" type="time" value={form.assembly} onChange={(v) => update('assembly', v)} /><TextField label="Gun start time" type="time" value={form.gunStart} onChange={(v) => update('gunStart', v)} /><TextField label="Cut-off time" type="time" value={form.cutoff} onChange={(v) => update('cutoff', v)} />{form.registrationClose && form.eventDate && form.registrationClose > form.eventDate && <p className="sm:col-span-2 rounded bg-red-50 p-3 text-sm text-red-700">Registration close must be before the event date.</p>}</div>}
    {step === 2 && <div className="mt-6 space-y-4"><div className="grid gap-4 sm:grid-cols-2"><TextField label="Venue name" value={form.venue} onChange={(v) => update('venue', v)} /><TextField label="City / Municipality" value={form.city} onChange={(v) => update('city', v)} /><TextField label="Province" value={form.province} onChange={(v) => update('province', v)} /></div><label className="block text-sm font-semibold">Full address<textarea value={form.address} onChange={(e) => update('address', e.target.value)} className={`${input} min-h-24`} /></label><Upload label="Route map image" value={form.routeMap} onChange={(file, url) => update('routeMap', { file, url })} wide /></div>}
    {step === 3 && <div className="mt-6 space-y-4"><p className="rounded bg-slate-50 p-3 text-sm">{categories.length} categories · <b>{capacity.toLocaleString()} total capacity</b></p>{categories.map((category, index) => <div key={index} className="grid gap-3 rounded-xl border p-4 sm:grid-cols-2"><TextField label="Category name" value={category.name} onChange={(v) => setCategories((c) => c.map((x, i) => i === index ? { ...x, name: v } : x))} /><TextField label="Distance (km)" type="number" value={category.distance} onChange={(v) => setCategories((c) => c.map((x, i) => i === index ? { ...x, distance: v } : x))} /><TextField label="Capacity" type="number" value={category.capacity} onChange={(v) => setCategories((c) => c.map((x, i) => i === index ? { ...x, capacity: v } : x))} /><TextField label="Fee (PHP)" type="number" value={category.fee} onChange={(v) => setCategories((c) => c.map((x, i) => i === index ? { ...x, fee: v } : x))} /><button onClick={() => setCategories((c) => c.filter((_, i) => i !== index))} className="text-left text-sm font-bold text-red-600">Delete category</button></div>)}<button onClick={() => setCategories((c) => [...c, emptyCategory()])} className="rounded-lg border border-orange-300 px-4 py-2 text-sm font-bold text-orange-700">+ Add another category</button></div>}
    {step === 4 && <div className="mt-6 space-y-4">{kits.map((kit, index) => <div key={index} className="flex gap-2"><input value={kit} onChange={(e) => setKits((c) => c.map((x, i) => i === index ? e.target.value : x))} placeholder="Race kit item" className={input} /><button onClick={() => setKits((c) => c.filter((_, i) => i !== index))} className="font-bold text-red-600">×</button></div>)}<button onClick={() => setKits((c) => [...c, ''])} className="rounded-lg border border-orange-300 px-4 py-2 font-bold text-orange-700">+ Add kit item</button></div>}
    {step === 5 && <div className="mt-6 space-y-4"><label className="block text-sm font-semibold">Event details<textarea value={form.description} onChange={(e) => update('description', e.target.value)} className={`${input} min-h-48`} /></label><label className="block text-sm font-semibold">Race mechanics<textarea value={form.mechanics} onChange={(e) => update('mechanics', e.target.value)} className={`${input} min-h-32`} /></label><Upload label="Event poster images (you can select multiple)" value={posters} multiple onChange={(file, url) => setPosters((current) => [...current, { file, url }])} /><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{posters.map((poster, index) => <div key={poster.url} className="relative"><img src={poster.url} alt={`Poster preview ${index + 1}`} className="aspect-square w-full rounded-lg object-cover" /><button type="button" onClick={() => setPosters((current) => current.filter((_, i) => i !== index))} className="absolute right-1 top-1 rounded-full bg-white px-2 py-1 text-xs font-bold text-red-600">×</button></div>)}</div>{faqs.map((faq, index) => <div key={index} className="rounded border p-3"><TextField label="Question" value={faq.question} onChange={(v) => setFaqs((c) => c.map((x, i) => i === index ? { ...x, question: v } : x))} /><label className="mt-2 block text-sm font-semibold">Answer<textarea value={faq.answer} onChange={(e) => setFaqs((c) => c.map((x, i) => i === index ? { ...x, answer: e.target.value } : x))} className={input} /></label></div>)}<button onClick={() => setFaqs((c) => [...c, { question: '', answer: '' }])} className="rounded-lg border border-orange-300 px-4 py-2 font-bold text-orange-700">+ Add FAQ</button></div>}
    {step === 6 && <div className="mt-6 space-y-5"><div className="grid gap-4 md:grid-cols-3">{Object.entries(sponsors).map(([tier, list]) => <div key={tier} className="rounded-xl border p-4"><h3 className="font-bold text-[#071b41]">{tier}</h3>{list.map((sponsor, index) => <div key={index} className="mt-3 space-y-2 rounded-lg bg-slate-50 p-3"><TextField label="Sponsor name" value={sponsor.name} onChange={(v) => editSponsor(tier, index, { name: v })} /><TextField label="Sponsor logo URL" value={sponsor.logo} onChange={(v) => editSponsor(tier, index, { logo: v })} /><TextField label="Website URL" value={sponsor.website} onChange={(v) => editSponsor(tier, index, { website: v })} /><button onClick={() => setSponsors((current) => ({ ...current, [tier]: list.filter((_, i) => i !== index) }))} className="text-sm font-bold text-red-600">Remove sponsor</button></div>)}<button onClick={() => addSponsor(tier)} className="mt-3 rounded-lg border border-orange-300 px-3 py-2 text-sm font-bold text-orange-700">+ Add sponsor</button></div>)}</div><div className="rounded-xl bg-slate-50 p-5 text-sm"><p>Event Profile {form.name ? '✓' : '⚠'}</p><p>Dates {form.eventDate ? '✓' : '⚠'}</p><p>Location {form.venue || form.address ? '✓' : '⚠'}</p><p>Categories {categories.length ? '✓' : '⚠'}</p><p>Kit and sponsor configuration are optional.</p><p className="mt-3">Event: <b>{form.name || 'Not provided'}</b> · Capacity: <b>{capacity || 'Not provided'}</b> · Posters: <b>{posters.length}</b></p></div><button disabled={busy || !ready} onClick={() => void createEvent()} className="rounded-lg bg-orange-600 px-4 py-2 text-sm font-bold text-white disabled:bg-slate-400">{busy ? 'Creating…' : 'Create Event'}</button></div>}
    <div className="mt-8 flex justify-between border-t pt-5"><button disabled={step === 0 || busy} onClick={() => setStep((s) => s - 1)} className="rounded-lg border px-4 py-2 text-sm font-bold disabled:opacity-40">← Back</button>{step < 6 && <button onClick={() => setStep((s) => s + 1)} className="rounded-lg bg-[#071b41] px-4 py-2 text-sm font-bold text-white">Next →</button>}</div></section></div></main>;
}
