'use client';

import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';

type Form = { name: string; logo_url: string; description: string; contact_person: string; contact_email: string; contact_phone: string; address: string; website: string; facebook: string; instagram: string; other: string };
const empty: Form = { name: '', logo_url: '', description: '', contact_person: '', contact_email: '', contact_phone: '', address: '', website: '', facebook: '', instagram: '', other: '' };

export default function OrganizationPage() {
  const router = useRouter();
  const [form, setForm] = useState<Form>(empty); const [message, setMessage] = useState('Loading organization…'); const [busy, setBusy] = useState(false);
  async function load() { const response = await fetch('/api/organizer/organization'); const body = await response.json().catch(() => ({})); if (!response.ok) { setMessage(body.error ?? 'Organization could not be loaded.'); return; } if (body.verification_status !== 'approved') { router.replace('/organizer/verification'); return; } const links = body.social_links ?? {}; setForm({ name: body.name ?? '', logo_url: body.logo_url ?? '', description: body.description ?? '', contact_person: body.contact_person ?? '', contact_email: body.contact_email ?? '', contact_phone: body.contact_phone ?? '', address: body.address ?? '', website: body.website ?? '', facebook: links.facebook ?? '', instagram: links.instagram ?? '', other: links.other ?? '' }); setMessage(''); }
  useEffect(() => { void load(); }, []);
  function set(key: keyof Form, value: string) { setForm((current) => ({ ...current, [key]: value })); }
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); const body = { name: form.name, logo_url: form.logo_url || null, description: form.description, contact_person: form.contact_person, contact_email: form.contact_email, contact_phone: form.contact_phone, address: form.address || null, website: form.website || null, social_links: { facebook: form.facebook, instagram: form.instagram, other: form.other } }; const response = await fetch('/api/organizer/organization', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json().catch(() => ({})); if (response.ok) await load(); setBusy(false); setMessage(response.ok ? 'Organization profile saved.' : result.error ?? 'Save failed.'); }
  async function upload(event: FormEvent<HTMLInputElement>) { const input = event.currentTarget; const file = input.files?.[0]; if (!file) return; setBusy(true); const data = new FormData(); data.append('file', file); const response = await fetch('/api/organizer/organization/logo', { method: 'POST', body: data }); const body = await response.json().catch(() => ({})); input.value = ''; if (response.ok) { await load(); set('logo_url', body.logo_url); } setBusy(false); setMessage(response.ok ? 'Logo uploaded and saved.' : body.error ?? 'Logo upload failed.'); }
  const required: Array<keyof Form> = ['name', 'contact_person', 'contact_email', 'contact_phone'];
  const missing = required.filter((key) => !form[key].trim()).map((key) => key.replaceAll('_', ' '));
  const ready = missing.length === 0 && Boolean(form.logo_url);
  return <main className="mx-auto max-w-4xl space-y-6 p-6"><header><p className="text-sm font-semibold uppercase tracking-[0.18em] text-orange-600">Organizer setup</p><h1 className="text-3xl font-semibold">Organization profile</h1><p className="mt-1 text-sm text-gray-600">This public information appears on your RaceDeck event pages.</p></header>{message && <p role="status" className="text-sm">{message}</p>}<form onSubmit={save} className="grid gap-4 rounded border bg-white p-6 sm:grid-cols-2">{required.map((key) => <label key={key} className="text-sm capitalize">{key.replaceAll('_', ' ')}<input required value={form[key]} onChange={(event) => set(key, event.target.value)} className="mt-1 w-full rounded border p-2" /></label>)}<label className="text-sm sm:col-span-2">Description<textarea required value={form.description} onChange={(event) => set('description', event.target.value)} className="mt-1 min-h-28 w-full rounded border p-2" /></label><label className="text-sm">Address<input value={form.address} onChange={(event) => set('address', event.target.value)} className="mt-1 w-full rounded border p-2" /></label><label className="text-sm">Website<input type="url" value={form.website} onChange={(event) => set('website', event.target.value)} className="mt-1 w-full rounded border p-2" /></label><label className="text-sm sm:col-span-2">Organization logo<input required={!form.logo_url} type="file" accept="image/jpeg,image/png,image/webp" onChange={upload} className="mt-1 block w-full rounded border p-2" />{form.logo_url && <img src={form.logo_url} alt="Organization logo" className="mt-2 h-16 w-16 rounded object-cover" />}</label><label className="text-sm">Facebook URL<input type="url" value={form.facebook} onChange={(event) => set('facebook', event.target.value)} className="mt-1 w-full rounded border p-2" /></label><label className="text-sm">Instagram URL<input type="url" value={form.instagram} onChange={(event) => set('instagram', event.target.value)} className="mt-1 w-full rounded border p-2" /></label><label className="text-sm sm:col-span-2">Other social URL<input type="url" value={form.other} onChange={(event) => set('other', event.target.value)} className="mt-1 w-full rounded border p-2" /></label><div className="sm:col-span-2"><button disabled={busy || !ready} className="rounded bg-black px-4 py-2 text-white disabled:opacity-50">{busy ? 'Saving…' : 'Save profile'}</button>{!ready && <p className="mt-2 text-xs text-gray-600">Complete the required fields and upload a logo before saving.</p>}</div></form><p className="text-sm text-gray-600">After completing your profile, continue to <a href="/organizer/verification" className="underline">verification</a>.</p></main>;
}
