'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';

type Payment = { id: string; status: string; amount_due: number; amount_paid: number; amount_refunded: number; currency: string; gateway: string; gateway_payment_id: string | null; checkout_url: string | null; expires_at: string | null; paid_at: string | null };
type RegistrationData = { registration: { id: string; registration_number: string; status: string; created_at: string; events: { name: string; event_date: string; venue: string | null; address: string | null } | null; race_categories: { name: string } | null; payments: Payment[]; payment_receipts: Array<{ id: string; receipt_reference: string }>; invoices: Array<{ id: string; invoice_reference: string; status: string }>; bibs: Array<{ bib_number: string; prefix: string | null }>; race_kit_claims: Array<{ claimed_at: string }>; results: Array<{ result_status: string; overall_rank: number | null }>; certificates: Array<{ certificate_reference: string; status: string }>; event_waiver_acceptances: Array<{ accepted_at: string }>; }; qr: { dataUrl: string } | null };
const label = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, item => item.toUpperCase());
const pendingPayment = (payment: Payment | undefined) => payment?.status === 'pending' || payment?.status === 'processing';

function Expiry({ expiresAt }: { expiresAt: string }) { const [now, setNow] = useState(Date.now()); useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 30_000); return () => window.clearInterval(timer); }, []); const seconds = Math.max(0, Math.floor((new Date(expiresAt).getTime() - now) / 1000)); return <span>{seconds > 0 ? `${Math.floor(seconds / 60)}m ${seconds % 60}s remaining` : 'Payment window expired'}</span>; }

export default function MyRaceDetailPage({ params }: { params: { registrationId: string } }) {
  const [data, setData] = useState<RegistrationData | null>(null); const [message, setMessage] = useState('Loading registration...');
  const load = useCallback(async () => { const response = await fetch(`/api/participant/my-races/${params.registrationId}`, { cache: 'no-store' }); const body = await response.json().catch(() => ({})); if (!response.ok) { setMessage(body.error ?? 'Registration could not be loaded.'); return; } setData(body as RegistrationData); setMessage(''); }, [params.registrationId]);
  useEffect(() => { void load(); }, [load]);
  const payment = useMemo(() => data?.registration.payments[0], [data]);
  useEffect(() => { if (!pendingPayment(payment)) return; const timer = window.setInterval(() => void load(), 15_000); return () => window.clearInterval(timer); }, [load, payment]);
  if (!data) return <main className="mx-auto max-w-4xl p-6"><p role="status" className="rounded-xl border border-slate-200 p-5 text-sm text-slate-600">{message}</p></main>;
  const row = data.registration; const paid = payment?.status === 'succeeded';
  return <main className="mx-auto max-w-5xl space-y-6 px-4 py-8 sm:px-6"><Link href="/my-races" className="text-sm font-semibold text-orange-600">← My Races</Link><header className="rounded-2xl bg-slate-950 p-6 text-white sm:p-8"><p className="text-sm font-semibold text-orange-200">Registration {row.registration_number}</p><h1 className="mt-2 text-3xl font-extrabold">{row.events?.name ?? 'Race event'}</h1><p className="mt-2 text-slate-200">{row.race_categories?.name ?? 'Category TBA'} • {row.events?.event_date ?? 'Date TBA'}</p><span className={`mt-4 inline-flex rounded-full px-3 py-1 text-sm font-bold ${row.status === 'confirmed' ? 'bg-emerald-400 text-emerald-950' : 'bg-amber-300 text-amber-950'}`}>{label(row.status)}</span></header>
    {pendingPayment(payment) && <section className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="text-lg font-bold text-amber-950">Payment pending</h2><p className="mt-2 text-sm text-amber-900">Your registration is reserved but not confirmed. RaceDeck will confirm it only after the payment gateway verifies your payment.</p>{payment?.expires_at && <p className="mt-3 text-sm font-semibold text-amber-950"><Expiry expiresAt={payment.expires_at} /></p>}{payment?.checkout_url && <a href={payment.checkout_url} className="mt-4 inline-block rounded-xl bg-orange-600 px-4 py-3 text-sm font-bold text-white">Continue to payment</a>}<button onClick={() => void load()} className="ml-3 mt-4 rounded-xl border border-amber-300 bg-white px-4 py-3 text-sm font-semibold text-amber-900">Refresh status</button></section>}
    {paid && row.status === 'confirmed' && <section className="grid gap-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-5 sm:grid-cols-[220px_1fr]"><div>{data.qr && <><img src={data.qr.dataUrl} alt="Secure registration QR" className="h-48 w-48 rounded-xl bg-white p-2" /><p className="mt-2 text-xs text-emerald-800">Registration QR — separate from your bib number.</p></>}</div><div><h2 className="text-xl font-bold text-emerald-950">Registration confirmed</h2><p className="mt-2 text-sm leading-6 text-emerald-900">Your payment was verified and your registration is confirmed. Present this QR at race-kit claiming when required.</p>{row.bibs[0] && <p className="mt-4 text-sm font-semibold text-emerald-950">Bib: {row.bibs[0].prefix ?? ''}{row.bibs[0].bib_number}</p>}</div></section>}
    <div className="grid gap-6 md:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold text-slate-900">Payment</h2><p className="mt-3 text-sm text-slate-600">{payment ? `${label(payment.status)} · ${payment.currency} ${Number(payment.amount_paid || payment.amount_due).toFixed(2)}` : 'Payment record pending'}</p>{payment && <p className="mt-2 text-xs text-slate-500">Method: {payment.gateway} · Transaction: {payment.gateway_payment_id ?? 'Pending'}</p>}{paid && payment && <div className="mt-4 flex flex-wrap gap-3 text-sm font-semibold text-orange-600"><a href={`/api/participant/payments/${payment.id}/receipt`}>Download Receipt</a>{row.invoices.some(invoice => invoice.status === 'issued') && <a href={`/api/participant/payments/${payment.id}/invoice`}>Download Invoice</a>}</div>}</section><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold text-slate-900">Race kit</h2><p className="mt-3 text-sm text-slate-600">{row.race_kit_claims[0] ? `Claimed ${new Date(row.race_kit_claims[0].claimed_at).toLocaleString()}` : 'Not yet claimed'}</p>{row.event_waiver_acceptances[0] && <p className="mt-2 text-xs text-slate-500">Event waiver accepted {new Date(row.event_waiver_acceptances[0].accepted_at).toLocaleDateString()}</p>}</section>{row.results[0] && <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold text-slate-900">Result</h2><p className="mt-3 text-sm text-slate-600">{label(row.results[0].result_status)}{row.results[0].overall_rank ? ` · Overall rank ${row.results[0].overall_rank}` : ''}</p></section>}{row.certificates[0] && <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold text-slate-900">Certificate</h2><p className="mt-3 text-sm text-slate-600">{row.certificates[0].certificate_reference} · {label(row.certificates[0].status)}</p></section>}</div></main>;
}
