import Link from 'next/link';
import { createAdminClient } from '@/lib/supabase/admin';
import { AdminPage, DataTable, EmptyState, StatCard, Toolbar, ActionLink, StatusBadge, Money } from '@/components/admin/admin-ui';

export default async function AdminParticipantsPage() {
  const db = createAdminClient();
  const { data: registrations } = await db.from('registrations').select('id,user_id,first_name,last_name,email,mobile,status,created_at,registration_number,events(id,name,event_date),payments(amount_paid,status)').order('created_at', { ascending: false }).limit(100);
  const rows = registrations ?? []; const unique = new Set(rows.map((row) => row.user_id ?? row.email)).size; const confirmed = rows.filter((row) => row.status === 'confirmed').length;
  return <AdminPage title="Participants" description="Search participant accounts and review their registration, payment, and race history." action={<Link href="/admin/participants" className="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-bold">Export current view</Link>}><section className="grid gap-4 sm:grid-cols-3"><StatCard label="Participants" value={unique} /><StatCard label="Registrations loaded" value={rows.length} /><StatCard label="Active registrations" value={confirmed} tone="green" /></section><Toolbar placeholder="Search name, email, registration ID, or bib..."><select aria-label="Registration status" className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option>All registration statuses</option><option>Confirmed</option><option>Pending payment</option><option>Cancelled</option></select></Toolbar>{rows.length ? <DataTable headers={['Participant','Contact','Event','Registration','Payment','Registered','Actions']}>{rows.map((row) => <tr key={row.id} className="hover:bg-slate-50"><td className="px-4 py-4"><p className="font-bold text-[#071b41]">{row.first_name} {row.last_name}</p><p className="mt-1 text-xs text-slate-500">{row.user_id ? 'Account participant' : 'Guest registration'}</p></td><td className="px-4 py-4 text-slate-600">{row.email}<br /><span className="text-xs">{row.mobile ?? 'No mobile'}</span></td><td className="px-4 py-4 font-semibold text-slate-700">{row.events?.name ?? '—'}</td><td className="px-4 py-4"><p className="font-mono text-xs">{row.registration_number}</p><StatusBadge value={row.status} /></td><td className="px-4 py-4"><StatusBadge value={row.payments?.status ?? 'not created'} /><p className="mt-1 text-xs text-slate-500"><Money value={Number(row.payments?.amount_paid ?? 0)} /></p></td><td className="px-4 py-4 text-xs text-slate-500">{new Date(row.created_at).toLocaleDateString('en-PH')}</td><td className="px-4 py-4"><ActionLink href={`/admin/participants/${row.user_id ?? row.id}`}>View</ActionLink></td></tr>)}</DataTable> : <EmptyState message="No participants found." />}</AdminPage>;
}
