import { NextResponse } from 'next/server';
import { requireOrganizerPermission } from '@/lib/auth/organizer-access';
const successfulStatuses = ['succeeded', 'partially_refunded', 'refunded'];
const csv = (value: unknown) => `"${String(value ?? '').replaceAll('"', '""')}"`;

export async function GET(request: Request) {
  const auth = await requireOrganizerPermission('view_financials'); if ('response' in auth) return auth.response;
  const params = new URL(request.url).searchParams; const eventFilter = params.get('eventId'); const statusFilter = params.get('status'); const exportCsv = params.get('export') === 'csv';
  const { data: allEvents, error: eventError } = await auth.admin.from('events').select('id,name').eq('organization_id', auth.membership.organization_id); if (eventError) return NextResponse.json({ error: 'Events could not be loaded' }, { status: 500 });
  const events = (allEvents ?? []).filter((event) => !auth.membership.restricted_event_ids || auth.membership.restricted_event_ids.includes(event.id)); const eventIds = events.filter((event) => !eventFilter || event.id === eventFilter).map((event) => event.id); if (eventFilter && !eventIds.length) return NextResponse.json({ error: 'Event is outside your organization scope' }, { status: 403 });
  let paymentsQuery = auth.admin.from('payments').select('id,event_id,registration_id,status,amount_due,amount_paid,amount_refunded,currency,gateway,gateway_payment_id,paid_at,created_at,registrations(first_name,last_name,email,registration_number),events(name)').in('event_id', eventIds).order('created_at', { ascending: false }).limit(1000); if (statusFilter) paymentsQuery = paymentsQuery.eq('status', statusFilter as never);
  const [{ data: payments, error }, { data: refunds, error: refundsError }, { data: fees, error: feesError }] = await Promise.all([eventIds.length ? paymentsQuery : Promise.resolve({ data: [], error: null }), eventIds.length ? auth.admin.from('refunds').select('id,event_id,payment_id,registration_id,status,amount,currency,gateway_refund_id,processed_at,created_at').in('event_id', eventIds).order('created_at', { ascending: false }).limit(1000) : Promise.resolve({ data: [], error: null }), eventIds.length ? auth.admin.from('platform_fees').select('id,event_id,payment_id,fee_type,status,amount,currency,collected_at,created_at').in('event_id', eventIds).order('created_at', { ascending: false }).limit(1000) : Promise.resolve({ data: [], error: null })]); if (error || refundsError || feesError) return NextResponse.json({ error: 'Financial records could not be loaded' }, { status: 500 });
  const paymentRows = payments ?? []; const paid = paymentRows.filter((row) => successfulStatuses.includes(row.status)); const gross = paid.reduce((sum, row) => sum + Number(row.amount_paid ?? 0), 0); const refunded = (refunds ?? []).filter((row) => row.status === 'succeeded').reduce((sum, row) => sum + Number(row.amount), 0); const feesTotal = (fees ?? []).filter((row) => ['accrued', 'collected'].includes(row.status)).reduce((sum, row) => sum + Number(row.amount), 0); const summary = { payments: paymentRows.length, successful_payments: paid.length, gross_paid: gross, refunds: refunded, platform_fees: feesTotal, net_revenue: gross - refunded - feesTotal };
  if (exportCsv) { const eventNames = new Map(events.map((event) => [event.id, event.name])); const rows = [['Payment ID', 'Event', 'Status', 'Currency', 'Amount Due', 'Amount Paid', 'Amount Refunded', 'Gateway', 'Paid At', 'Created At'], ...paymentRows.map((row) => [row.id, eventNames.get(row.event_id) ?? row.event_id, row.status, row.currency, row.amount_due, row.amount_paid, row.amount_refunded, row.gateway, row.paid_at ?? '', row.created_at])]; return new NextResponse(rows.map((row) => row.map(csv).join(',')).join('\r\n'), { headers: { 'Content-Type': 'text/csv; charset=utf-8', 'Content-Disposition': 'attachment; filename="racedeck-payments.csv"' } }); }
  return NextResponse.json({ events, payments: paymentRows, refunds: refunds ?? [], fees: fees ?? [], summary });
}
