'use client';

import Link from 'next/link';
import { useState } from 'react';

type PendingOrganizer = { organization_id: string; submitted_at: string | null; organization_name: string };

export default function PendingOrganizers({ initialItems }: { initialItems: PendingOrganizer[] }) {
  const [items, setItems] = useState(initialItems); const [busyId, setBusyId] = useState<string | null>(null); const [message, setMessage] = useState('');
  async function approve(item: PendingOrganizer) { if (!window.confirm(`Approve ${item.organization_name}?`)) return; setBusyId(item.organization_id); setMessage(''); const response = await fetch(`/api/admin/organizers/${item.organization_id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: 'approved', reviewer_notes: null }) }); const body = await response.json().catch(() => ({})); setBusyId(null); if (!response.ok) { setMessage(body.error ?? 'Approval failed.'); return; } setItems(current => current.filter(value => value.organization_id !== item.organization_id)); setMessage(`${item.organization_name} approved successfully.`); }
  return <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 px-5 py-4"><div><h2 className="font-bold text-slate-950">Organizer applications awaiting review</h2><p className="mt-1 text-sm text-slate-500">Review documents or approve submitted organizer accounts.</p></div><Link href="/admin/organizers" className="text-sm font-semibold text-orange-600">View all →</Link></div>{message && <p role="status" className="border-b border-slate-100 px-5 py-3 text-sm text-slate-700">{message}</p>}{items.length ? <div className="divide-y divide-slate-100">{items.map(item => <div key={item.organization_id} className="flex flex-wrap items-center justify-between gap-3 px-5 py-4"><div><p className="font-semibold text-slate-900">{item.organization_name}</p><p className="text-xs text-slate-500">Submitted {item.submitted_at ? new Date(item.submitted_at).toLocaleDateString() : 'date unavailable'}</p></div><div className="flex gap-2"><Link href={`/admin/organizers/${item.organization_id}`} className="rounded-lg border px-3 py-2 text-sm font-semibold">Review</Link><button disabled={busyId === item.organization_id} onClick={() => void approve(item)} className="rounded-lg bg-emerald-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">{busyId === item.organization_id ? 'Approving…' : 'Approve'}</button></div></div>)}</div> : <p className="px-5 py-10 text-center text-sm text-slate-500">No organizer applications are waiting for review.</p>}</section>;
}
