import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from '@/types/database.types';

export function localAdmin(): SupabaseClient<Database> { const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY; if (!url || !key || (!url.includes('127.0.0.1') && !url.includes('localhost'))) throw new Error('Integration tests require local Supabase credentials in .env.test'); return createClient<Database>(url, key, { auth: { autoRefreshToken: false, persistSession: false } }); }

export async function seedLocalFixture() { const admin = localAdmin(); const suffix = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`; const organizer = await admin.auth.admin.createUser({ email: `organizer-${suffix}@example.test`, password: 'RaceDeck-test-123!', email_confirm: true }); const participant = await admin.auth.admin.createUser({ email: `participant-${suffix}@example.test`, password: 'RaceDeck-test-123!', email_confirm: true }); if (organizer.error || participant.error || !organizer.data.user || !participant.data.user) { throw new Error(`Could not create local test users: ${organizer.error?.message ?? participant.error?.message ?? 'missing user'}`); } const { data: organization } = await admin.from('organizations').insert({ name: `Test Org ${suffix}`, slug: `test-org-${suffix}`, created_by: organizer.data.user.id }).select('id').single(); if (!organization) throw new Error('Could not create organization'); await admin.from('organization_members').insert({ organization_id: organization.id, user_id: organizer.data.user.id, role: 'owner' }); const { data: event } = await admin.from('events').insert({ organization_id: organization.id, name: `Test Event ${suffix}`, slug: `test-event-${suffix}`, event_date: '2099-01-01', lifecycle_status: 'published', review_status: 'approved', registration_availability: 'open' }).select('id').single(); if (!event) throw new Error('Could not create event'); const { data: category } = await admin.from('race_categories').insert({ event_id: event.id, name: '5K', registration_fee: 500, registration_availability: 'open' }).select('id').single(); if (!category) throw new Error('Could not create category'); const { data: registration } = await admin.from('registrations').insert({ registration_number: `TEST-${suffix}`, event_id: event.id, category_id: category.id, user_id: participant.data.user.id, status: 'confirmed', first_name: 'Test', last_name: 'Participant', email: participant.data.user.email ?? `participant-${suffix}@example.test` }).select('id').single(); if (!registration) throw new Error('Could not create confirmed registration'); return { admin, organizer: organizer.data.user, participant: participant.data.user, organization, event, category, registration }; }

export async function cleanupLocalFixture(fixture: Awaited<ReturnType<typeof seedLocalFixture>>) { if (!fixture) return; await fixture.admin.from('registrations').delete().eq('id', fixture.registration.id); await fixture.admin.from('organizations').delete().eq('id', fixture.organization.id); await fixture.admin.auth.admin.deleteUser(fixture.organizer.id); await fixture.admin.auth.admin.deleteUser(fixture.participant.id); }

export async function seedSecondOrganization(admin: SupabaseClient<Database>) { const suffix = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`; const created = await admin.auth.admin.createUser({ email: `organizer-b-${suffix}@example.test`, password: 'RaceDeck-test-123!', email_confirm: true }); if (!created.data.user) throw new Error(`Could not create second organizer: ${created.error?.message ?? 'missing user'}`); const { data: organization } = await admin.from('organizations').insert({ name: `Test Org B ${suffix}`, slug: `test-org-b-${suffix}`, created_by: created.data.user.id }).select('id').single(); if (!organization) throw new Error('Could not create second organization'); await admin.from('organization_members').insert({ organization_id: organization.id, user_id: created.data.user.id, role: 'owner' }); return { user: created.data.user, organization }; }

export async function createLocalParticipant(admin: SupabaseClient<Database>) { const suffix = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`; const created = await admin.auth.admin.createUser({ email: `participant-extra-${suffix}@example.test`, password: 'RaceDeck-test-123!', email_confirm: true }); if (!created.data.user) throw new Error(`Could not create test participant: ${created.error?.message ?? 'missing user'}`); return created.data.user; }
