import Link from 'next/link';
import { getPublicEvents, type PublicEventCard } from '@/lib/public/events';

const statusLabel = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, letter => letter.toUpperCase());
const formatDate = (value: string) => new Intl.DateTimeFormat('en-PH', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value.includes('T') ? value : `${value}T00:00:00`));
const eventHref = (event: PublicEventCard) => `/events/${event.slug}`;

function StatusPill({ status }: { status: string }) {
  const color = status === 'open' ? 'bg-emerald-50 text-emerald-700 ring-emerald-200' : status === 'sold_out' ? 'bg-amber-50 text-amber-700 ring-amber-200' : 'bg-slate-100 text-slate-700 ring-slate-200';
  return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ring-1 ring-inset ${color}`}>{statusLabel(status)}</span>;
}

function EventVisual({ event, featured = false }: { event: PublicEventCard; featured?: boolean }) {
  return <div className={`relative overflow-hidden bg-slate-900 ${featured ? 'h-60 md:h-72' : 'h-44'}`}>
    {event.banner_url ? <img src={event.banner_url} alt={`${event.name} banner`} className="h-full w-full object-cover" /> : <div className="h-full w-full bg-gradient-to-br from-slate-950 via-slate-800 to-orange-700" />}
    <div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 via-slate-950/10 to-transparent" />
    <div className="absolute inset-x-0 bottom-0 p-5 text-white"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-orange-200">{featured ? 'Featured race' : event.organizer?.name ?? 'RaceDeck event'}</p><h2 className={featured ? 'mt-1 text-3xl font-bold md:text-4xl' : 'mt-1 text-xl font-bold'}>{event.name}</h2></div>
  </div>;
}

export default async function EventsPage({ searchParams }: { searchParams: Record<string, string | string[] | undefined> }) {
  const get = (key: string) => { const value = searchParams[key]; return Array.isArray(value) ? value[0] : value; };
  const page = Number(get('page') ?? '1');
  const data = await getPublicEvents({ search: get('search'), location: get('location'), distance: get('distance'), status: get('status'), sort: get('sort'), page: Number.isFinite(page) ? page : 1 });
  const paginationHref = (next: number) => { const query = new URLSearchParams(); for (const key of ['search', 'location', 'distance', 'status', 'sort']) { const value = get(key); if (value) query.set(key, value); } query.set('page', String(next)); return `/events?${query}`; };

  return <main className="mx-auto max-w-7xl space-y-8 px-4 py-8 sm:px-6">
    <header className="space-y-2"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-orange-600">Find your next finish line</p><h1 className="text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">Upcoming Events</h1><p className="max-w-2xl text-slate-600">Discover verified RaceDeck events, compare categories, and view full race details before you register.</p></header>

    <section className="grid gap-6 lg:grid-cols-[260px_1fr]">
      <aside className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><h2 className="text-lg font-bold text-slate-900">Upcoming Events</h2><p className="mt-1 text-sm text-slate-600">Browse races happening soon.</p><div className="mt-5 space-y-3">{data.events.slice(0, 4).map(event => <Link key={event.id} href={eventHref(event)} className="block rounded-xl bg-white p-3 transition hover:bg-orange-50 hover:text-orange-700"><span className="block text-sm font-semibold">{event.name}</span><span className="mt-1 block text-xs text-slate-500">{formatDate(event.event_date)}</span></Link>)}</div><Link href="#all-events" className="mt-5 inline-block text-sm font-semibold text-orange-600 hover:text-orange-700">Browse events →</Link></aside>
      <div>{data.featured ? <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><Link href={eventHref(data.featured)} className="block focus:outline-none focus:ring-2 focus:ring-orange-500 focus:ring-offset-2"><EventVisual event={data.featured} featured /><div className="flex flex-wrap items-center justify-between gap-4 p-5"><div className="text-sm text-slate-600"><span>{formatDate(data.featured.event_date)}</span><span className="mx-2">•</span><span>{data.featured.venue ?? data.featured.address ?? 'Location to be announced'}</span></div><div className="flex gap-2"><span className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700">View Details</span><span className="rounded-lg bg-orange-600 px-3 py-2 text-sm font-semibold text-white">Register Now →</span></div></div></Link></article> : <div className="rounded-2xl border border-dashed border-slate-300 p-10 text-center text-slate-600">No featured event is available yet.</div>}</div>
    </section>

    <form className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-5" method="get"><input name="search" defaultValue={get('search')} placeholder="Search events" className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /><input name="location" defaultValue={get('location')} placeholder="All locations" className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /><input name="distance" defaultValue={get('distance')} placeholder="Distance (km)" className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /><select name="status" defaultValue={get('status') ?? ''} className="rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="">All registration status</option>{['not_yet_open', 'open', 'closed', 'sold_out'].map(status => <option key={status} value={status}>{statusLabel(status)}</option>)}</select><select name="sort" defaultValue={get('sort') ?? ''} className="rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="">Soonest date</option><option value="date_desc">Latest date</option><option value="name">Name</option></select><input type="hidden" name="page" value="1" /><button className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white md:col-span-5 md:justify-self-end">Apply filters</button></form>

    <section id="all-events"><div className="mb-5 flex items-end justify-between gap-4"><div><h2 className="text-2xl font-bold text-slate-900">All Events</h2><p className="mt-1 text-sm text-slate-600">Find your next race. Challenge yourself and enjoy the journey.</p></div><span className="text-sm text-slate-500">{data.total} event{data.total === 1 ? '' : 's'}</span></div>{data.events.length ? <div className="grid gap-6 sm:grid-cols-2 xl:grid-cols-3">{data.events.map(event => <article key={event.id} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><Link href={eventHref(event)} className="block h-full focus:outline-none focus:ring-2 focus:ring-orange-500 focus:ring-inset"><EventVisual event={event} /><div className="space-y-3 p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-slate-500">{formatDate(event.event_date)}</p><p className="mt-1 text-sm text-slate-600">{event.venue ?? event.address ?? 'Location to be announced'}</p></div><StatusPill status={event.registration_availability} /></div><div className="flex flex-wrap gap-2">{event.distances.length ? event.distances.map(distance => <span key={distance} className="rounded-full border border-orange-200 bg-orange-50 px-2 py-1 text-xs font-semibold text-orange-700">{distance}K</span>) : <span className="text-xs text-slate-500">Categories to be announced</span>}</div>{event.registration_closes_at && <p className="text-xs text-slate-500">Registration closes {formatDate(event.registration_closes_at)}</p>}{event.starting_registration_fee !== null && <p className="text-sm font-semibold text-slate-900">From ₱{event.starting_registration_fee.toFixed(2)}</p>}<div className="flex items-center justify-between gap-3 border-t border-slate-100 pt-3"><span className="text-sm font-semibold text-slate-700">View Details</span><span className="rounded-lg bg-orange-600 px-3 py-2 text-sm font-semibold text-white">Register Now →</span></div></div></Link></article>)}</div> : <p className="rounded-2xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-600">No events match the selected filters.</p>}</section>

    <nav className="flex items-center gap-4 text-sm font-semibold text-slate-700">{data.page > 1 && <Link href={paginationHref(data.page - 1)} className="rounded-lg border border-slate-200 px-3 py-2 hover:bg-slate-50">Previous</Link>}{data.page < data.totalPages && <Link href={paginationHref(data.page + 1)} className="rounded-lg border border-slate-200 px-3 py-2 hover:bg-slate-50">Next</Link>}</nav>
  </main>;
}
