'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';

export type OrganizerApplication = { organizationId: string; status: string; submittedAt: string | null; organization: { name: string; accountStatus: string; verificationStatus: string } };
const statuses = ['pending_review', 'needs_changes', 'approved', 'rejected', 'draft'];

export default function OrganizerListClient({ initialApplications }: { initialApplications: OrganizerApplication[] }) {
  const [status, setStatus] = useState('pending_review'); const [items, setItems] = useState(initialApplications); const [message, setMessage] = useState('');
  useEffect(() => { if (status === 'pending_review') { setItems(initialApplications); return; } void fetch(`/api/admin/organizers?status=${status}`).then(async response => { const data = await response.json().catch(() => []); if (!response.ok) throw new Error(data.error ?? 'Applications could not be loaded'); return data; }).then((rows: Array<{ organization_id: string; status: string; submitted_at: string | null; organizations: { name: string; account_status: string; verification_status: string } | null }>) => { setItems(rows.map(row => ({ organizationId: row.organization_id, status: row.status, submittedAt: row.submitted_at, organization: { name: row.organizations?.name ?? 'Unnamed organization', accountStatus: row.organizations?.account_status ?? 'unknown', verificationStatus: row.organizations?.verification_status ?? row.status } }))); setMessage(''); }).catch(error => setMessage(error instanceof Error ? error.message : 'Applications could not be loaded')); }, [initialApplications, status]);
  return <main className="mx-auto max-w-6xl space-y-6 p-6"><header><h1 className="text-2xl font-semibold">Organizer Verification</h1><p className="text-sm text-gray-600">Review submitted organizer applications.</p></header><label className="block w-fit text-sm">Verification status<select value={status} onChange={event => setStatus(event.target.value)} className="mt-1 block rounded border p-2">{statuses.map(value => <option key={value} value={value}>{value.replaceAll('_', ' ')}</option>)}</select></label>{message && <p role="alert" className="text-sm text-red-600">{message}</p>}<div className="overflow-x-auto rounded border"><table className="w-full text-left text-sm"><thead className="border-b bg-gray-50"><tr><th className="p-3">Organization</th><th className="p-3">Verification</th><th className="p-3">Account</th><th className="p-3">Submitted</th></tr></thead><tbody>{items.map(item => <tr key={item.organizationId} className="border-b last:border-0 hover:bg-gray-50"><td className="p-3"><Link href={`/admin/organizers/${item.organizationId}`} className="font-medium underline">{item.organization.name}</Link></td><td className="p-3">{item.status.replaceAll('_', ' ')}</td><td className="p-3">{item.organization.accountStatus}</td><td className="p-3">{item.submittedAt ? new Date(item.submittedAt).toLocaleString() : 'Not submitted'}</td></tr>)}{items.length === 0 && <tr><td className="p-4 text-gray-600" colSpan={4}>No organizer applications found.</td></tr>}</tbody></table></div></main>;
}
