'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';

export type OrganizerApplication = { organizationId: string; status: string; submittedAt: string | null; organization: { name: string; accountStatus: string; verificationStatus: string } };
const statuses = ['pending_review', 'needs_changes', 'approved', 'rejected', 'draft'];

export default function OrganizerListClient({ initialApplications }: { initialApplications: OrganizerApplication[] }) {
  const [status, setStatus] = useState('all'); const [items, setItems] = useState(initialApplications); const [message, setMessage] = useState(''); const [busyId, setBusyId] = useState<string | null>(null);
  useEffect(() => { if (status === 'all') { setItems(initialApplications); return; } void fetch(`/api/admin/organizers?status=${status}`).then(async response => { const data = await response.json().catch(() => []); if (!response.ok) throw new Error(data.error ?? 'Applications could not be loaded'); return data; }).then((rows: Array<{ organization_id: string; status: string; submitted_at: string | null; organizations: { name: string; account_status: string; verification_status: string } | null }>) => setItems(rows.map(row => ({ organizationId: row.organization_id, status: row.status, submittedAt: row.submitted_at, organization: { name: row.organizations?.name ?? 'Unnamed organization', accountStatus: row.organizations?.account_status ?? 'unknown', verificationStatus: row.organizations?.verification_status ?? row.status } })))).catch(error => setMessage(error instanceof Error ? error.message : 'Applications could not be loaded')); }, [initialApplications, status]);
  async function approve(application: OrganizerApplication) { if (!window.confirm(`Approve ${application.organization.name}?`)) return; setBusyId(application.organizationId); setMessage(''); const response = await fetch(`/api/admin/organizers/${application.organizationId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: 'approved', reviewer_notes: null }) }); const data = await response.json().catch(() => ({})); setBusyId(null); if (!response.ok) { setMessage(data.error ?? 'Approval failed.'); return; } setItems(current => current.filter(item => item.organizationId !== application.organizationId)); setMessage(`${application.organization.name} approved successfully.`); }
  return <main className="mx-auto max-w-7xl space-y-6 bg-[#f4f6fa] p-6"><header><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[11px] font-extrabold uppercase tracking-[0.2em] text-orange-600">Platform / Management</p><h1 className="text-3xl font-black text-[#071b41]">Organizers</h1><p className="text-sm text-gray-600">Review, verify, and manage organizations using RaceDeck.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-sm font-semibold text-slate-700">{items.length} visible</span></div></header><div className="flex flex-wrap items-end gap-3"><label className="text-sm font-semibold">Verification status<select value={status} onChange={event => setStatus(event.target.value)} className="mt-1 block rounded-lg border border-slate-300 bg-white p-2 font-normal"><option value="all">All organizers</option>{statuses.map(value => <option key={value} value={value}>{value.replaceAll('_', ' ')}</option>)}</select></label><input placeholder="Search organization or contact..." className="rounded-lg border border-slate-300 p-2 text-sm" /></div>{message && <p role="status" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{message}</p>}<div className="overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b bg-slate-50"><tr><th className="p-3">Organization</th><th className="p-3">Verification</th><th className="p-3">Account</th><th className="p-3">Submitted</th><th className="p-3">Actions</th></tr></thead><tbody>{items.map(item => <tr key={item.organizationId} className="border-b last:border-0 hover:bg-gray-50"><td className="p-3"><Link href={`/admin/organizers/${item.organizationId}`} className="font-bold text-[#071b41]">{item.organization.name}</Link></td><td className="p-3 capitalize">{item.status.replaceAll('_', ' ')}</td><td className="p-3 capitalize">{item.organization.accountStatus}</td><td className="p-3">{item.submittedAt ? new Date(item.submittedAt).toLocaleString() : 'Not submitted'}</td><td className="p-3"><div className="flex flex-wrap gap-2"><Link href={`/admin/organizers/${item.organizationId}`} className="rounded border px-3 py-1.5 text-xs font-bold">Review</Link>{item.status === 'pending_review' && <button disabled={busyId === item.organizationId} onClick={() => void approve(item)} className="rounded bg-emerald-700 px-3 py-1.5 text-xs font-bold text-white disabled:opacity-50">{busyId === item.organizationId ? 'Approving...' : 'Approve'}</button>}</div></td></tr>)}{items.length === 0 && <tr><td className="p-6 text-center text-gray-600" colSpan={5}>No organizer applications found.</td></tr>}</tbody></table></div></main>;
}
